export const bellIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></svg>';
export function visibleNotices(notices,mode,adminPortal=false){return notices.filter(n=>!['like','favorite'].includes(n.event_kind)&&!(mode==='seller'&&!adminPortal&&['professional_login','professional_join','login','sign_in'].includes(n.event_kind)));}
export function unreadCount(notices,offers,seen){return visibleNotices(notices).filter(n=>!n.read_at).length+offers.filter(o=>!seen.has(o.order_id)).length;}
export function interactionControls(productId,rows,E){return `<div class="ac-reactions">${[['favorite','☆','المفضلة'],['like','♡','أعجبني']].map(([kind,icon,label])=>{const active=rows.some(r=>r.product_id===productId&&r.kind===kind);return `<button data-a="react" data-v="${E(productId)}|${kind}" aria-pressed="${active}">${active?(kind==='favorite'?'★':'♥'):icon} ${label}</button>`}).join('')}</div>`;}
export function createActivityCenter(ctx){
 const E=ctx.esc;let owner=null,rows=[],offers=[],interactions=[],seen=new Set(),open=false,busy=false,generation=0,loaded=false,interactionVersion=0;const reactionBusy=new Set();
 const get=()=>ctx.get();
 function reset(id){generation++;owner=id;rows=[];offers=[];interactions=[];seen=new Set();loaded=false;busy=false;open=false;document.getElementById('activityPanel')?.remove();try{seen=new Set(JSON.parse(localStorage.getItem('souq-offers-read-'+id)||'[]'))}catch{}}
 function sync(){const g=get(),id=g.user?.id||null;if(owner!==id)reset(id);const enabled=!!id&&!g.profile?.disabled&&(g.adminPortal?g.profile?.role==='admin':['seller','driver'].includes(g.mode));let button=document.getElementById('activityBell');if(!enabled){button?.remove();if(!id||g.profile?.disabled){document.getElementById('activityPanel')?.remove();open=false;}return;}if(!button){button=document.createElement('button');button.id='activityBell';button.className='ac-floating';button.dataset.a='notifications';button.innerHTML=bellIcon+'<span data-notice-count hidden></span>';button.setAttribute('aria-label','الإشعارات');button.setAttribute('aria-controls','activityPanel');document.body.append(button);}paint();if(!loaded)poll().catch(ctx.error);}
 function paint(){const count=unreadCount(rows,offers,seen);document.querySelectorAll('[data-notice-count]').forEach(el=>{el.hidden=!count;el.textContent=count>99?'99+':count});document.getElementById('activityBell')?.setAttribute('aria-expanded',String(open));if(open)paintPanel();}
 async function poll(){const g=get();if(!g.user||g.profile?.disabled||busy||document.hidden)return;const id=g.user.id;if(owner!==id)reset(id);const gen=generation,version=interactionVersion;busy=true;try{
  const results=await Promise.all([ctx.db.from('account_notifications').select('*').eq('recipient_id',id).not('event_kind','in','(like,favorite)').order('created_at',{ascending:false}).limit(100),ctx.db.from('product_interactions').select('product_id,kind').eq('user_id',id),g.mode==='driver'&&g.driver?.approved?ctx.db.rpc('delivery_offer_details'):Promise.resolve({data:[]})]);
  const values=results.map(ctx.check);if(gen!==generation||get().user?.id!==id)return;rows=visibleNotices(values[0]||[],g.mode,g.adminPortal);if(g.adminPortal)rows=rows.filter(n=>n.event_kind!=='professional_login'||!rows.some(join=>join.event_kind==='professional_join'&&join.event_key.split(':').slice(1,4).filter((_,i)=>i!==1).join(':')===n.event_key.split(':').slice(1,4).filter((_,i)=>i!==1).join(':')&&new Date(join.created_at)>=new Date(n.created_at)));if(version===interactionVersion)interactions=values[1]||[];offers=values[2]||[];loaded=true;ctx.offers?.(offers);paint();if(open&&!document.hidden)await markViewed();
 }finally{if(gen===generation)busy=false;}}
 function close(){open=false;document.getElementById('activityPanel')?.remove();paint();document.getElementById('activityBell')?.focus();}
 function paintPanel(){let panel=document.getElementById('activityPanel');if(!panel){panel=document.createElement('aside');panel.id='activityPanel';panel.className='ac-panel';panel.setAttribute('role','dialog');panel.setAttribute('aria-label','مركز الإشعارات');document.body.append(panel);}panel.innerHTML=`<header><div><b>الإشعارات <span class="ac-unread-label">${rows.filter(n=>!n.read_at).length} جديدة</span></b><small>${get().adminPortal?'دخول الحسابات وطلبات الانضمام':'الطلبات وتحديثات الموقع والتحذيرات والمستحقات'}</small></div><button data-n="close" aria-label="الرجوع إلى الواجهة السابقة">→</button></header><div class="ac-panel-tools"><button data-n="refresh">تحديث</button><button data-n="read">تعليم الكل كمقروء</button></div><div class="ac-feed">${offers.map(o=>`<button class="ac-notice ${seen.has(o.order_id)?'':'unread'}" data-n="offer" data-v="${E(o.order_id)}"><b>طلب متاح للتوصيل · ${E(o.store_name)}</b><span>${E((o.items||[]).map(i=>i.name+' × '+i.quantity).join('، '))}</span><small>${E(ctx.fmt(o.product_total))} · افتح لقبول الطلب</small></button>`).join('')}${rows.map(n=>{const parts=n.event_key.split(':'),can=get().adminPortal&&n.event_kind==='professional_join'&&ctx.canApproveProfessional?.(parts[1],parts[3]);return `<article><button class="ac-notice ${n.read_at?'':'unread'}" data-n="notice" data-v="${E(n.id)}"><b><span class="ac-notice-kind">${E(({inventory:"المخزون",payment:"المستحقات",order:"الطلبات",app_update:"تحديث التطبيق",warning:"تحذير"})[n.event_kind]||(n.order_id?"الطلبات":"تحديث"))}</span>${E(n.title)}</b><span>${E(n.body)}</span><small>${E(ctx.when(n.created_at))}</small></button>${can?`<button class="buy ac-accept" data-n="approve" data-v="${E(n.id)}">قبول الطلب مباشرة</button>`:''}</article>`;}).join('')}${!offers.length&&!rows.length?'<p class="ac-empty">لا توجد إشعارات بعد. ستظهر هنا الطلبات وتحديثات الموقع والتحذيرات والمخزون والمستحقات.</p>':''}</div><footer>تتحدث الإشعارات كل ٢٠ ثانية أثناء فتح التطبيق.</footer>`;}
 async function markViewed(){
  const id=owner,gen=generation;if(!id||get().user?.id!==id||!open||document.hidden)return;
  // Only acknowledge the feed actually shown, never newer/unloaded notifications.
  const ids=rows.filter(n=>!n.read_at).map(n=>n.id),viewedOffers=offers.map(o=>o.order_id),readAt=new Date().toISOString();
  if(ids.length)ctx.check(await ctx.db.from('account_notifications').update({read_at:readAt}).eq('recipient_id',id).in('id',ids).is('read_at',null));
  if(gen!==generation||get().user?.id!==id)return;
  const readIds=new Set(ids);rows.forEach(n=>{if(readIds.has(n.id)&&!n.read_at)n.read_at=readAt;});
  viewedOffers.forEach(orderId=>seen.add(orderId));saveSeen();paint();
 }
 async function markAll(){await markViewed();await poll();}
 function saveSeen(){try{localStorage.setItem('souq-offers-read-'+owner,JSON.stringify([...seen].slice(-200)))}catch{}}
 async function show(){const id=get().user?.id;if(!id){ctx.login();return;}if(owner!==id)reset(id);open=true;paint();await poll();document.querySelector('#activityPanel [data-n="close"]')?.focus();}
 document.addEventListener('click',e=>{const button=e.target.closest('[data-n]');if(!button)return;const action=button.dataset.n;ctx.run(async()=>{if(action==='close')close();if(action==='refresh')await poll();if(action==='read')await markAll();if(action==='offer'){seen.add(button.dataset.v);saveSeen();close();ctx.driverOrders();}if(action==='approve'&&get().adminPortal){const n=rows.find(r=>r.id===button.dataset.v);if(!n||n.event_kind!=='professional_join'||button.disabled)return;const parts=n.event_key.split(':');button.disabled=true;try{await ctx.approveProfessional?.(parts[1],parts[3]);ctx.check(await ctx.db.from('account_notifications').update({read_at:new Date().toISOString()}).eq('id',n.id).eq('recipient_id',owner));await poll();}finally{if(button.isConnected)button.disabled=false;}}if(action==='notice'){const n=rows.find(r=>r.id===button.dataset.v);if(!n)return;ctx.check(await ctx.db.from('account_notifications').update({read_at:new Date().toISOString()}).eq('id',n.id).eq('recipient_id',owner));n.read_at=new Date().toISOString();close();if(n.event_kind==='delivery_offer')ctx.driverOrders();else if(n.order_id)await ctx.order(n.order_id);else if(n.product_id)ctx.product(n.product_id);else if(get().adminPortal){if(['professional_login','professional_join'].includes(n.event_kind)){const parts=n.event_key.split(':');ctx.professional?.(parts[1],parts[3]);}}else if(get().mode==='driver')ctx.driverOrders();}});});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&open)close();});
 document.addEventListener('visibilitychange',()=>{if(!document.hidden&&get().user)poll().catch(ctx.error);});
 setInterval(()=>{if(get().user&&(!get().adminPortal||get().profile?.role==='admin'))poll().catch(()=>{});},20000);
 async function react(productId,kind){const g=get();if(!g.user||g.mode==='guest'){ctx.login();return false;}const key=productId+'|'+kind;if(g.profile?.disabled||!['favorite','like'].includes(kind)||reactionBusy.has(key))return false;reactionBusy.add(key);const active=interactions.some(r=>r.product_id===productId&&r.kind===kind);try{ctx.check(await (active?ctx.db.from('product_interactions').delete().eq('user_id',g.user.id).eq('product_id',productId).eq('kind',kind):ctx.db.from('product_interactions').insert({user_id:g.user.id,product_id:productId,kind})));if(get().user?.id!==g.user.id)return false;interactionVersion++;interactions=interactions.filter(r=>r.product_id!==productId||r.kind!==kind);if(!active)interactions.push({product_id:productId,kind});paint();return true;}finally{reactionBusy.delete(key);}}
 return {sync,show,close,poll,react,controls:id=>interactionControls(id,interactions,E),favorites:()=>interactions.filter(r=>r.kind==='favorite').map(r=>r.product_id)};
}

