/* Public marketplace presentation. Products keep their original seller and ID. */
(()=>{
'use strict';
const icons={cart:'<path d="M3 4h2l2 12h11l3-9H6M11 10h6M14 7v6"/><circle cx="9" cy="20" r="1"/><circle cx="17" cy="20" r="1"/>',materials:'<path d="m3 7 9-4 9 4v10l-9 4-9-4ZM3 7l9 4 9-4M12 11v10M7 5l9 4"/>',stores:'<path d="M3 10h18l-2-7H5zM4 10v11h16V10M9 21v-7h6v7M3 10q2 4 4 0 2 4 5 0 3 4 5 0 2 4 4 0"/>'};
const icon=name=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.materials}</svg>`;
const variantOffers=p=>p.has_variants&&!p.selectedVariant&&(p.variants||[]).some(v=>!v.archived&&v.available&&v.sale_price>0&&v.sale_price<v.price);
const discounted=p=>variantOffers(p)||Number.isSafeInteger(p.compare_at_price)&&p.compare_at_price>p.price&&p.price>0;
const percent=p=>discounted(p)?Math.max(1,Math.round((1-p.price/p.compare_at_price)*100)):0;
function price(p,fmt){return `<span class="mp-price"><strong>${p.has_variants&&!p.selectedVariant?'ابتداءً من ':''}${fmt(p.price)}</strong>${discounted(p)&&!variantOffers(p)?`<del>${fmt(p.compare_at_price)}</del>`:''}</span>`;}
function badge(p){if(variantOffers(p))return '<span class="mp-discount">عروض للنسخ</span>';return discounted(p)?`<span class="mp-discount">تخفيض ${percent(p)}٪</span>`:'';}
function avatar(m,esc){return `<span class="mp-store-avatar">${m.image_url?.startsWith('https://')?`<img src="${esc(m.image_url)}" alt="صورة ${esc(m.name)}" loading="lazy" decoding="async">`:icon('stores')}</span>`;}
function switcher(active='market'){return `<nav class="mp-switcher" aria-label="تصفح السوق"><button data-a="marketSection" data-v="materials" aria-pressed="${active==='materials'}">${icon('materials')}<span><b>المواد</b><small>منتجات جميع التجار</small></span></button><button data-a="marketSection" data-v="stores" aria-pressed="${active==='stores'}">${icon('stores')}<span><b>المتاجر</b><small>اختر متجرًا وتصفح مواده</small></span></button></nav>`;}
function storeCards(stores,products,{esc}){return `<div class="mp-stores">${stores.map(m=>{const items=products.filter(p=>p.mid===m.id&&p.active&&!p.blocked),deals=items.filter(discounted).length;return `<a class="mp-store-card" href="./?store=${encodeURIComponent(m.id)}" data-a="visitStore" data-v="${esc(m.id)}">${avatar(m,esc)}<div><h3>${esc(m.name)}</h3>${m.username?`<small dir="ltr">@${esc(m.username)}</small>`:""}<p>${esc(m.description||m.address||'متجر في سوق الشطرة')}</p><span>${items.length} منتج${deals?` · ${deals} عرض`:''}</span></div><span class="mp-visit">زيارة المتجر ←</span></a>`;}).join('')}</div>`;}
function productFace(p,{esc,fmt,thumb}){return `<div class="mp-card-photo">${thumb(p)}${badge(p)}<span class="boutique-availability"><i aria-hidden="true"></i>${forSale(p)?'متوفر':'غير متوفر'}</span></div><div class="mp-card-body"><span class="mp-card-cart" aria-hidden="true">${icon('cart')}</span><h3>${esc(p.name)}</h3>${p.variant?`<small class="mp-card-variant">${esc(p.variant)}</small>`:''}${price(p,fmt)}${p.stock<1?'<small class="mp-unavailable">نفدت الكمية</small>':''}${window.SouqBoutique?.previewOptions(p,{esc})||''}</div>`;}
function productCards(products,{esc,fmt,thumb,mname,favorites=[]}){return `<div class="grid mp-products">${products.map(p=>`<article class="mp-product">${favoriteButton(p,esc,favorites)}${quickAddButton(p,esc)}<button class="mp-product-open" data-a="prod" data-v="${esc(p.id)}" aria-label="عرض ${esc(p.name)}">${productFace(p,{esc,fmt,thumb})}</button><a class="mp-product-store" href="./?store=${encodeURIComponent(p.mid)}" data-a="visitStore" data-v="${esc(p.mid)}">${icon('stores')}<span>${esc(mname(p.mid))}</span><span aria-hidden="true">←</span></a></article>`).join('')}</div>`;}

function quickAddButton(p,esc){return `<button type="button" class="market-card-plus" data-a="quickAdd" data-v="${esc(p.id)}" aria-label="إضافة ${esc(p.name)} إلى السلة" ${forSale(p)?'':'disabled'}>+</button>`;}
function favoriteButton(p,esc,favorites=[]){const active=favorites.includes(p.id);return `<button type="button" class="boutique-favorite" data-a="cardFavorite" data-v="${esc(p.id)}" aria-label="${active?'إزالة من المفضلة':'إضافة إلى المفضلة'}" aria-pressed="${active}"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 20 4 12a5 5 0 0 1 8-6 5 5 0 0 1 8 6Z"/></svg></button>`;}

const normalizeSearch=value=>window.SouqCatalog.normalize(value).replace(/ة/g,'ه');
function oneEdit(a,b){if(Math.abs(a.length-b.length)>1)return false;let i=0,j=0,n=0;while(i<a.length&&j<b.length){if(a[i]===b[j]){i++;j++;continue}if(++n>1)return false;if(a.length>=b.length)i++;if(b.length>=a.length)j++;}return n+(i<a.length||j<b.length?1:0)<=1;}
function searchRank(text,query){const name=normalizeSearch(text),terms=normalizeSearch(query).split(' ').filter(Boolean);if(!terms.length)return 0;let rank=0;for(const term of terms){if(name.startsWith(term)){continue}if(name.split(' ').some(w=>w.startsWith(term))){rank+=1;continue}if(name.includes(term)){rank+=2;continue}if(term.length>=3&&name.split(' ').some(w=>oneEdit(w,term)||oneEdit(w.slice(0,term.length),term))){rank+=4;continue}return Infinity;}return rank;}
const forSale=p=>p.active&&!p.blocked&&(p.has_variants?(p.variants||[]).some(v=>!v.archived&&v.available&&v.stock>0):p.stock>0);
function searchProducts(products,stores,query){const names=new Map(stores.map(m=>[m.id,m.name]));return products.map((p,i)=>({p,i,rank:Math.min(searchRank(p.name,query),searchRank(names.get(p.mid),query),searchRank([p.name,p.desc,p.variant,p.sku].join(' '),query)+3)})).filter(x=>Number.isFinite(x.rank)).sort((a,b)=>a.rank-b.rank||a.i-b.i).map(x=>x.p);}
function searchStores(stores,products,query){return stores.map((m,i)=>{const items=products.filter(p=>p.mid===m.id),matching=searchProducts(items,[{...m,name:''}],query),nameRank=searchRank(m.name,query),rank=Math.min(nameRank,...matching.map(p=>searchRank(p.name,query)+1));return {store:m,products:Number.isFinite(nameRank)?items:matching,rank,i};}).filter(x=>Number.isFinite(x.rank)).sort((a,b)=>a.rank-b.rank||a.i-b.i);}
function suggestions(products,stores,query,scope){if(!normalizeSearch(query))return [];const list=[...products.map(p=>({kind:'product',id:p.id,label:p.name,seller:stores.find(m=>m.id===p.mid)?.name||'',rank:searchRank(p.name,query)})),...stores.map(m=>({kind:'store',id:m.id,label:m.name,seller:'',rank:searchRank(m.name,query)}))].filter(x=>Number.isFinite(x.rank));const primary=scope==='stores'?'store':'product';list.sort((a,b)=>(a.kind!==primary)-(b.kind!==primary)||a.rank-b.rank||a.label.localeCompare(b.label,'ar'));return list.slice(0,8);}
function storeMatches(rows,options){return rows.map(({store:m,products})=>`<section class="mp-search-store"><header><a href="./?store=${encodeURIComponent(m.id)}" data-a="visitStore" data-v="${options.esc(m.id)}">${avatar(m,options.esc)}<h3>${options.esc(m.name)}</h3></a><span>${products.length} مادة مطابقة</span></header>${products.length?productCards(products,options):'<p class="note">لا توجد مواد متوفرة حاليًا.</p>'}</section>`).join('');}

window.SouqMarketplace={favoriteButton,forSale,searchRank,searchProducts,searchStores,suggestions,storeMatches,icon,discounted,price,badge,avatar,switcher,storeCards,productCards,productFace,quickAddButton};
})();



