import {categoryDefinitions,variantKey,variantLabel} from './product-variants.js?v=110';
import {COLOR_PALETTE,OPTION_ICONS,customDefinitions,validateCustom,suggestions,validateAttributeValue} from './product-options.js?v=103';
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const field=(id,label,value='',extra='')=>`<div class="va-field"><label for="${id}">${E(label)}</label><input id="${id}" value="${E(value??'')}" ${extra}></div>`;
const opt=(a,v)=>a.map(([k,t])=>`<option value="${E(k)}" ${k===v?'selected':''}>${E(t)}</option>`).join('');
const num='type="number" min="0" max="2147483647" step="1" inputmode="numeric"';
const uuid=()=>{if(crypto.randomUUID)return crypto.randomUUID();const bytes=crypto.getRandomValues(new Uint8Array(16));bytes[6]=(bytes[6]&15)|64;bytes[8]=(bytes[8]&63)|128;const h=Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');return h.slice(0,8)+'-'+h.slice(8,12)+'-'+h.slice(12,16)+'-'+h.slice(16,20)+'-'+h.slice(20);};
export function createProductEditor({categories,upload,toast,base}){
 let s,host,advanced;
 const defs=()=>[...categoryDefinitions(categories(),s.category),...s.custom].filter((d,i,a)=>a.findIndex(x=>x.key===d.key)===i);
 const fresh=stock=>({id:uuid(),attributes:{},price:base().price,stock:stock??0,available:true,archived:false,inherit:true});
 function mount(el,p){host=el;advanced=document.getElementById('productSpecs');const c=categories().find(c=>c.id===p?.catalog_category_id),meta=p?.attributes?._selling||{};
  s={root:c?.parent_id||c?.id||categories().find(c=>!c.parent_id&&c.name===p?.cat)?.id||((p?.cat||meta.section)?'other':''),category:c?.id||'',section:meta.section||p?.cat||'',subcategory:meta.subcategory||'',custom:structuredClone(customDefinitions(p?.attributes)),attrs:{...(p?.attributes||{})},enabled:!!p?.has_variants,rows:(p?.variants||[]).map(v=>({...v,attributes:{...v.attributes},discount:v.sale_price!=null,inherit:p?.attributes?._manual_variants===true?(p.attributes._variant_inherit||[]).includes(v.id):false})),axes:[],baseId:p?.attributes?._base_variant_id||null,legacyStock:p?.stock};
  s.axes=[...new Set(s.rows.filter(v=>!v.archived).flatMap(v=>Object.keys(v.attributes)))];
  if(!s.baseId&&s.rows.length)s.baseId=s.rows.find(v=>!v.archived)?.id;
  if(s.enabled&&!s.rows.length){const v=fresh(p?.stock);s.rows.push(v);s.baseId=v.id;}
  render();
 }
 function ensureAxis(key,label){const existing=defs().find(d=>d.key===key&&d.variant);if(existing)return existing.key;const k='custom_'+key;if(!s.custom.some(d=>d.key===k))s.custom.push({key:k,label,icon:key==='color'?'🎨':key==='size'?'📏':'🏷️',type:'text',options:[],variant:true,required:false});return k;}
 function standard(){return [['color','اللون'],['type','النوع'],['size','المقاس / الحجم'],['material','المادة / الخامة']].map(([key,label])=>({key:defs().find(d=>d.key===key&&d.variant)?.key||'custom_'+key,label,source:key}));}
 const keyAttrs=v=>Object.fromEntries(s.axes.map(k=>[k,String(v.attributes[k]||'').trim()]));
 function updateStock(){const n=document.getElementById('fs');if(n){n.disabled=s.enabled;if(s.enabled)n.value=s.rows.filter(v=>!v.archived&&v.available).reduce((a,v)=>a+(Number(v.stock)||0),0);}}
 function row(v,i){const d=defs(),isBase=v.id===s.baseId,attr=k=>`data-ve-row="${i}" data-ve-field="${k}"`;
  const identity=s.axes.map(k=>{const a=d.find(d=>d.key===k),vals=k==='color'||k==='custom_color'?COLOR_PALETTE.map(c=>c[0]):suggestions(a||{key:k},s.category,categories());return field('ve'+i+k,isBase?'ما هو '+(a?.label||k)+' للنسخة الأساسية؟':a?.label||k,v.attributes[k],`maxlength="500" data-ve-row="${i}" data-ve-attribute="${E(k)}" list="vl${i}${E(k)}"`)+`<datalist id="vl${i}${E(k)}">${vals.map(x=>`<option value="${E(x)}">`).join('')}</datalist>`;}).join('');
  if(isBase)return `<fieldset class="va-row va-base"><legend>خصائص النسخة الأساسية</legend><div class="va-fields">${identity}</div><p class="note">تستخدم الاسم والصورة والسعر والمعلومات التي أدخلتها للمنتج.</p></fieldset>`;
  return `<fieldset class="va-row ${v.archived?'va-archived':''}"><legend>نسخة ${i+1}${v.archived?' · مؤرشفة':''}</legend><div class="va-fields">${identity}${field('vstock'+i,'مخزون هذه النسخة',v.stock,num+' '+attr('stock'))}</div><label class="va-check"><input type="checkbox" ${attr('inherit')} ${!v.inherit?'checked':''}>سعر هذه النسخة مختلف</label>${!v.inherit?field('vprice'+i,v.discount?'السعر قبل التخفيض (د.ع)':'سعر هذه النسخة (د.ع)',v.price,num+' '+attr('price')):'<p class="note">تستخدم سعر المنتج الرئيسي تلقائيًا.</p>'}<label class="va-check"><input type="checkbox" ${attr('discount')} ${v.discount?'checked':''}>هل يوجد تخفيض لهذه النسخة؟</label>${v.discount?field('vsale'+i,'السعر بعد التخفيض (د.ع)',v.sale_price,num+' '+attr('sale_price')):''}<label for="vimage${i}">صورة مختلفة لهذه النسخة (اختياري)</label><input id="vimage${i}" type="file" accept="image/*" ${attr('image_path')}>${v.preview||v.img?`<img class="va-image" src="${E(v.preview||v.img)}" alt="صورة النسخة">`:'<p class="note">تستخدم صورة المنتج الرئيسية ما لم تضف صورة مختلفة.</p>'}${v.image_path||v.file?`<button type="button" data-ve="inheritImage" data-index="${i}">استخدام الصورة الرئيسية</button>`:''}<details class="va-panel"><summary>إعدادات هذه النسخة</summary><div class="va-fields">${field('vsku'+i,'SKU',v.sku,'maxlength="80" '+attr('sku'))}${field('vbarcode'+i,'Barcode',v.barcode,'maxlength="80" '+attr('barcode'))}${field('vweight'+i,'وزن الشحن بالكغم',v.weight,'type="number" min="0" step="any" '+attr('weight'))}</div><label class="va-check"><input type="checkbox" ${attr('available')} ${v.available?'checked':''}>متاحة للبيع</label></details><button type="button" class="alt" data-ve="archive" data-index="${i}">${v.archived?'استعادة النسخة':'أرشفة النسخة'}</button></fieldset>`;
 }
 function render(){const cats=categories(),roots=cats.filter(c=>!c.parent_id&&(c.active||c.id===s.root)&&(c.name!=='أخرى'||c.id===s.root)),children=cats.filter(c=>c.parent_id===s.root&&(c.active||c.id===s.category));
  host.innerHTML=`<h2>القسم والفئة</h2><label for="vaRoot">القسم *</label><select id="vaRoot" required>${opt([['','اختر القسم'],...roots.map(c=>[c.id,c.name]),['other','أخرى']],s.root)}</select>${s.root==='other'?field('veSection','اسم القسم',s.section,'maxlength="80" required'):s.root?`<label for="vaCategory">الفئة (اختيارية)</label><select id="vaCategory">${opt([['','بدون فئة'],...children.map(c=>[c.id,c.name]),['other','أخرى']],s.subcategory?'other':s.category===s.root?'':s.category)}</select>`:''}${s.root==='other'||s.subcategory||s.subcategoryMode?field('veSubcategory','اسم الفئة',s.subcategory,'maxlength="80"'):''}<h2>المخزون ونظام النسخ</h2><label class="va-check"><input id="vaEnabled" type="checkbox" ${s.enabled?'checked':''}>يوجد لهذا المنتج نسخ</label>${s.enabled?`<p class="note">اختر ما تختلف به النسخ، ثم أضف النسخ الموجودة لديك فقط. لا تُنشأ تركيبات تلقائية.</p><div class="va-axes">${standard().map(d=>`<label class="va-check"><input type="checkbox" data-ve-axis="${E(d.source)}" ${s.axes.includes(d.key)?'checked':''}>${E(d.label)}</label>`).join('')}<label class="va-check"><input id="veOther" type="checkbox" ${s.otherOpen?'checked':''}>أخرى</label></div>${s.otherOpen?field('veAxisName','اسم الخاصية','','maxlength="80" placeholder="مثال: السعة التخزينية"')+'<button type="button" data-ve="addAxis">إضافة خاصية للنسخ</button>':''}${s.axes.filter(k=>!standard().some(d=>d.key===k)).map(k=>`<p>${E(defs().find(d=>d.key===k)?.label||k)} <button type="button" data-ve="removeAxis" data-key="${E(k)}">إزالة من النسخ</button></p>`).join('')}${field('veBaseStock','مخزون النسخة الأساسية',s.rows.find(v=>v.id===s.baseId)?.stock??0,num+' data-ve-row="'+s.rows.findIndex(v=>v.id===s.baseId)+'" data-ve-field="stock"')}<div class="va-rows">${s.rows.map(row).join('')}</div><button type="button" class="alt" data-ve="addRow">＋ إضافة ${s.axes.length===1?(defs().find(d=>d.key===s.axes[0])?.label||'نسخة'): "نسخة"} جديدة</button>`:''}`;
  if(advanced)advanced.innerHTML=`<h3>مواصفات وفلاتر المنتج</h3><p class="note">استخدم ما يناسب المنتج فقط.</p><div class="va-fields">${defs().filter(d=>d.key!=='sale_unit'&&!s.axes.includes(d.key)).map(d=>field('vaAttr'+d.key,(d.icon||'')+' '+d.label,s.attrs[d.key],`data-ve-spec="${E(d.key)}" maxlength="500" ${d.type==='number'?'type="number" min="0" step="any"':d.type==='date'?'type="date"':''} list="sp${E(d.key)}"`)+`<datalist id="sp${E(d.key)}">${suggestions(d,s.category,categories()).map(v=>`<option value="${E(v)}">`).join('')}</datalist>`).join('')}</div><h3>خصائص مخصصة</h3>${s.custom.map((d,i)=>`<fieldset class="va-row">${field('customLabel'+i,'اسم الخاصية',d.label,`data-ve-custom="${i}" data-custom-field="label" maxlength="80"`)}<label>الأيقونة<select data-ve-custom="${i}" data-custom-field="icon">${opt(OPTION_ICONS.map(x=>[x,x]),d.icon)}</select></label><label>نوع القيمة<select data-ve-custom="${i}" data-custom-field="type">${opt([['text','نص'],['select','خيارات'],['number','رقم'],['date','تاريخ']],d.type)}</select></label>${field('customOptions'+i,'قيم مقترحة مفصولة بفاصلة',d.options.join('، '),`data-ve-custom="${i}" data-custom-field="options"`)}<button type="button" data-ve="removeCustom" data-index="${i}">إزالة الخاصية</button></fieldset>`).join('')}<button type="button" data-ve="addSpec">＋ خاصية مخصصة</button>`;
  for(const el of [host,advanced].filter(Boolean)){el.oninput=input;el.onchange=change;el.onclick=click;}updateStock();
 }
 function input(e){const t=e.target,k=t.dataset;if(t.id==='veSection')s.section=t.value;if(t.id==='veSubcategory')s.subcategory=t.value;if(k.veSpec)s.attrs[k.veSpec]=t.value;if(k.veAttribute){s.rows[+k.veRow].attributes[k.veAttribute]=t.value;return;}if(k.veCustom!==undefined){const d=s.custom[+k.veCustom];d[k.customField]=k.customField==='options'?[...new Set(t.value.split(/[,،\n]/).map(v=>v.trim()).filter(Boolean))]:t.value;}if(k.veRow!==undefined&&t.type!=='file'){const v=s.rows[+k.veRow],f=k.veField;v[f]=f==='inherit'?!t.checked:t.type==='checkbox'?t.checked:t.value;updateStock();}}
 function removeAxis(k){if(s.rows.some(v=>v.version&&!v.archived&&v.attributes[k])){toast('أرشف النسخ المستخدمة قبل إزالة الخاصية حفاظًا على مخزونها');return false;}s.axes=s.axes.filter(x=>x!==k);for(const v of s.rows)if(!v.version)delete v.attributes[k];return true;}
 function change(e){const t=e.target,k=t.dataset;input(e);
  if(t.id==='vaRoot'||t.id==='vaCategory'){const root=t.id==='vaRoot'?t.value:s.root,category=t.id==='vaRoot'?(root==='other'?'':root):(t.value==='other'?s.root:t.value||s.root);if(s.rows.some(v=>!v.archived&&v.version)){const next=[...categoryDefinitions(categories(),category),...s.custom];if(s.axes.some(k=>!next.some(d=>d.key===k&&d.variant))){toast('التصنيف الجديد لا يدعم خصائص النسخ الحالية. أرشف النسخ أولًا أو احتفظ بالقسم.');render();return;}}s.root=root;s.category=category;s.subcategoryMode=t.id==='vaCategory'&&t.value==='other';if(!s.subcategoryMode)s.subcategory='';render();}
  if(t.id==='vaEnabled'){if(!t.checked&&s.rows.some(v=>v.version)){toast('النسخ محفوظة بسجلها؛ استخدم أرشفة النسخة أو المنتج لإيقاف البيع');render();return;}s.enabled=t.checked;if(s.enabled&&!s.rows.length){const v=fresh(Number(document.getElementById('fs')?.value)||0);s.rows.push(v);s.baseId=v.id;}render();}
  if(k.veAxis){const a=standard().find(d=>d.source===k.veAxis);if(t.checked){const id=ensureAxis(k.veAxis,a.label);if(!s.axes.includes(id))s.axes.push(id);const v=s.rows.find(v=>v.id===s.baseId);if(v&&!v.attributes[id]&&s.attrs[k.veAxis])v.attributes[id]=s.attrs[k.veAxis];}else removeAxis(a.key);render();}
  if(t.id==='veOther'){s.otherOpen=t.checked;render();}
  if(k.veRow!==undefined&&['inherit','discount'].includes(k.veField)){const v=s.rows[+k.veRow];if(k.veField==='discount'){if(v.discount){v.inherit=false;v.price=v.price||base().price;}else v.sale_price=null;}render();}
  if(k.veCustom!==undefined&&k.customField==='type')render();
  if(t.type==='file'&&k.veRow!==undefined&&t.files?.[0]){const v=s.rows[+k.veRow],f=t.files[0];if(!f.type.startsWith('image/')||f.size>10485760){toast('اختر صورة أقل من ١٠ ميغابايت');return;}if(v.preview)URL.revokeObjectURL(v.preview);v.file=f;v.preview=URL.createObjectURL(f);render();}
 }
 function click(e){const b=e.target.closest('[data-ve]');if(!b)return;e.preventDefault();const {ve,index,key}=b.dataset;
  if(ve==='addRow'){if(s.rows.length>=200){toast('الحد الأقصى ٢٠٠ نسخة');return;}s.rows.push(fresh(0));}
  if(ve==='archive'){const v=s.rows[+index];v.archived=!v.archived;}
  if(ve==='inheritImage'){const v=s.rows[+index];if(v.preview)URL.revokeObjectURL(v.preview);v.file=null;v.preview=null;v.image_path=null;v.img=null;}
  if(ve==='removeAxis')removeAxis(key);
  if(ve==='addAxis'||ve==='addSpec'){if(ve==='addAxis'){const label=document.getElementById('veAxisName').value.trim(),existing=defs().find(d=>d.label.trim().toLocaleLowerCase()===label.toLocaleLowerCase());if(existing){const custom=s.custom.find(d=>d.key===existing.key);if(!existing.variant&&!custom){toast('هذه الخاصية موجودة ضمن المواصفات؛ اختر اسمًا آخر للنسخ');return;}if(custom)custom.variant=true;if(!s.axes.includes(existing.key))s.axes.push(existing.key);render();return;}}if(s.custom.length>=20){toast('الحد الأقصى ٢٠ خاصية مخصصة');return;}const label=ve==='addAxis'?document.getElementById('veAxisName').value.trim():'خاصية جديدة';if(!label){toast('اكتب اسم الخاصية');return;}const k='custom_'+uuid().replaceAll('-','');s.custom.push({key:k,label,icon:'🏷️',type:'text',options:[],variant:ve==='addAxis',required:false});if(ve==='addAxis')s.axes.push(k);}
  if(ve==='removeCustom'){const d=s.custom[+index];if(!removeAxis(d.key))return;delete s.attrs[d.key];s.custom.splice(+index,1);}
  render();
 }
 async function collect(){if(!s.root||(s.root==='other'&&!s.section.trim()))throw Error('اختر القسم أو اكتب اسمه');if((s.subcategoryMode||s.root==='other')&&s.subcategory.length>80)throw Error('اسم الفئة طويل');validateCustom(s.custom);const ds=defs(),attrs={...s.attrs};for(const d of ds)if(attrs[d.key])validateAttributeValue(d,attrs[d.key]);for(const k of s.axes)if(s.enabled)delete attrs[k];attrs._custom_options=s.custom;attrs._manual_variants=true;attrs._base_variant_id=s.baseId;attrs._selling={...(attrs._selling||{}),section:s.root==='other'?s.section.trim():categories().find(c=>c.id===s.root)?.name,subcategory:s.subcategory.trim()};
  const rows=s.enabled?s.rows:[],keys=new Set(),skus=new Set(),saved=[];if(s.enabled&&(!s.axes.length||!rows.some(v=>!v.archived)))throw Error('اختر خاصية للنسخ وأضف نسخة واحدة على الأقل');if(s.axes.length>12)throw Error('الحد الأقصى ١٢ خاصية للنسخ');
  for(const v of rows){const a=v.archived?v.attributes:keyAttrs(v);if(!v.archived){if(Object.values(a).some(x=>!x))throw Error('حدد خصائص كل نسخة');for(const [k,value]of Object.entries(a)){const d=ds.find(d=>d.key===k);if(!d?.variant)throw Error('خاصية غير صالحة للنسخ');validateAttributeValue(d,value);}const identity=variantKey(a);if(keys.has(identity))throw Error('هذه النسخة مكررة؛ عدّل مخزون النسخة الموجودة');keys.add(identity);}
   const isBase=v.id===s.baseId,main=base(),price=Number(isBase?(main.compare_at_price||main.price):v.inherit?main.price:v.price),stock=Number(v.stock),sale=isBase?(main.compare_at_price?Number(main.price):null):v.discount&&v.sale_price!==''&&v.sale_price!=null?Number(v.sale_price):null,weight=v.weight===''||v.weight==null?null:Number(v.weight);if(v.stock===''||![price,stock].every(Number.isSafeInteger)||price<1||price>2147483647||stock<0||stock>2147483647||sale!==null&&(!Number.isSafeInteger(sale)||sale<=0||sale>=price)||weight!==null&&(!Number.isFinite(weight)||weight<0))throw Error('راجع سعر ومخزون النسخة');const sku=(v.sku||'').trim();if(!v.archived&&sku){if(skus.has(sku))throw Error('SKU مكرر بين النسخ');skus.add(sku);}saved.push({id:v.id,version:v.version,attributes:a,label:v.archived?v.label:variantLabel(a,ds),price,sale_price:sale,stock,weight,sku,barcode:(v.barcode||'').trim(),available:!!v.available,archived:!!v.archived,image_path:v.file?await upload(v.file):v.image_path||null});
  }attrs._variant_inherit=rows.filter(v=>v.inherit).map(v=>v.id);if(saved.filter(v=>!v.archived&&v.available).reduce((a,v)=>a+v.stock,0)>2147483647)throw Error('إجمالي المخزون أكبر من الحد المسموح');if(new TextEncoder().encode(JSON.stringify(attrs)).length>20000)throw Error('الخصائص طويلة جدًا');return {catalog_category_id:s.root==='other'?null:s.category||s.root,category:attrs._selling.section,attributes:attrs,variants:saved,expected_stock:s.legacyStock};
 }
 return {mount,collect,hasVariants:()=>!!s?.enabled};
}

