const CF=[['identity','معلومات الزبون'],['group','المجموعة والوسوم'],['first','تاريخ أول طلب'],['address','العنوان'],['average','متوسط قيمة الطلب'],['count','عدد الطلبات'],['created','تاريخ الإنشاء']];
export function createSellerRecords(ctx,h){
 const {E,btn,icon,modal,select,empty,saveConfig,getSettings}=h,$=s=>document.querySelector(s);
 let categories=[],saved=[],page='',query='',catFilter={active:'all',deleted:'active'},filter={deleted:'active'},storeId=null;
 const store=()=>ctx.get().store,products=()=>ctx.get().data.p.filter(p=>p.mid===store()?.id),orders=()=>ctx.get().data.o.filter(o=>o.mid===store()?.id);
 async function load(id){if(storeId!==id){page='';query='';filter={deleted:'active'};catFilter={active:'all',deleted:'active'};storeId=id;}if(!id||!ctx.get().canSell){categories=[];saved=[];return;}const out=await Promise.all([ctx.db.from('seller_categories').select('*').eq('store_id',id).order('created_at'),ctx.db.from('seller_customers').select('*').eq('store_id',id).order('created_at')]);out.forEach(ctx.check);if(storeId!==id)return;categories=out[0].data||[];saved=out[1].data||[];}
 const key=o=>o.buyer_id?'buyer:'+o.buyer_id:'phone:'+o.cust.phone.replace(/\D/g,'');
 function customers(){const map=new Map(saved.map(c=>[c.customer_key,{...c,orders:[]}]));for(const o of orders()){const k=key(o);if(!map.has(k))map.set(k,{customer_key:k,buyer_id:o.buyer_id,name:o.cust.name,phone:o.cust.phone,address:o.cust.addr,province:'',tags:[],customer_group:'',note:'',created_at:o.ts,orders:[]});map.get(k).orders.push(o);}return [...map.values()].map(c=>{const complete=c.orders.filter(o=>o.st===3);return {...c,count:c.orders.length,first:c.orders.length?c.orders.map(o=>o.ts).sort()[0]:null,average:complete.length?complete.reduce((s,o)=>s+o.total,0)/complete.length:0};});}
 const visibleDeleted=(r,v)=>v==='both'||(v==='deleted'?!!r.deleted_at:!r.deleted_at);
 function customerList(){return customers().filter(c=>visibleDeleted(c,filter.deleted)&&(!filter.province||c.province===filter.province)&&(!filter.tag||c.tags.includes(filter.tag))&&(!filter.group||c.customer_group===filter.group)&&(!filter.activity||(filter.activity==='orders'?c.count>0:c.count===0))&&(!filter.blocked||(filter.blocked==='yes'?c.blocked:!c.blocked))&&(!query||[c.name,c.phone,c.address,...c.tags].join(' ').toLowerCase().includes(query.toLowerCase())));}
 function title(label,act){return `<header class="sw-header"><div class="sw-store-id"><button class="sw-icon" data-s="recordsBack" aria-label="رجوع">${icon('home')}</button><h1>${label}</h1></div>${btn(act,icon('plus'),'','sw-add')}</header>`;}
 function search(kind){return `<form id="swRecordsSearch" data-kind="${kind}" class="sw-search"><input id="swRecordsQuery" type="search" aria-label="بحث" placeholder="ابحث بالاسم أو الهاتف" value="${E(query)}"><button aria-label="بحث">${icon('search')}</button></form>`;}
 function categoryPage(){const rows=categories.filter(c=>visibleDeleted(c,catFilter.deleted)&&(catFilter.active==='all'||c.active===(catFilter.active==='yes'))&&(!query||c.name.includes(query)));return title('تصنيفات المتجر','categoryForm')+search('categories')+`<div class="sw-toolbar">${btn('categoryFilters',icon('filter')+'تصفية')}<span>${rows.length} تصنيف</span></div><div class="sw-record-grid">${rows.map(c=>`<article class="sw-card"><div class="sw-card-title"><h2>${E(c.name)}</h2>${btn('categoryForm','تعديل',c.id)}</div><p>${products().filter(p=>p.cat===c.name).length} منتج</p><div class="sw-actions">${c.deleted_at?btn('categoryRestore','استعادة',c.id):btn('categoryToggle',c.active?'فعال · تعطيل':'غير فعال · تفعيل',c.id)+btn('categoryDelete','حذف',c.id)}</div>${btn('categoryProducts','عرض المنتجات',c.name)}</article>`).join('')||empty('لا توجد تصنيفات مطابقة')}</div>`;}
 function customerPage(){const fields=getSettings().customerFields||CF.map(x=>x[0]);const list=customerList();return title('العملاء','customerForm')+search('customers')+`<div class="sw-toolbar">${btn('customerFilters',icon('filter')+'تصفية')}${btn('customerFields',icon('columns')+'المعلومات الظاهرة')}<span>${list.length} عميل</span></div><div class="sw-record-grid">${list.map(c=>`<article class="sw-card sw-customer">${fields.includes('identity')?`<h2>${E(c.name)}</h2><a dir="ltr" href="tel:${E(c.phone)}">${E(c.phone)}</a>`:''}${c.blocked?'<span class="sw-status status-4">محظور من الطلب في هذا المتجر</span>':''}${c.deleted_at?'<span class="sw-muted">مؤرشف</span>':''}${fields.includes('group')?`<p>${E(c.customer_group||'دون مجموعة')} ${c.tags.map(t=>`<span class="sw-tag">${E(t)}</span>`).join('')}</p>`:''}${fields.includes('address')?`<p>${E([c.province,c.address].filter(Boolean).join(' · '))}</p>`:''}<dl class="sw-record-details">${fields.includes('count')?`<div><dt>عدد الطلبات</dt><dd>${c.count}</dd></div>`:''}${fields.includes('average')?`<div><dt>متوسط الطلب المكتمل</dt><dd>${ctx.fmt(c.average)}</dd></div>`:''}${fields.includes('first')?`<div><dt>أول طلب</dt><dd>${c.first?E(ctx.when(c.first)):'—'}</dd></div>`:''}${fields.includes('created')?`<div><dt>تاريخ الإنشاء</dt><dd>${E(ctx.when(c.created_at))}</dd></div>`:''}</dl>${c.note?`<p>${E(c.note)}</p>`:''}<div class="sw-actions">${btn('customerForm','تعديل',c.customer_key)}${c.deleted_at?btn('customerRestore','استعادة',c.customer_key):btn('customerDelete','أرشفة',c.customer_key)}${c.buyer_id?btn('customerBlock',c.blocked?'رفع الحظر':'حظر الطلب',c.customer_key):''}</div></article>`).join('')||empty('لا يوجد عملاء مطابقون')}</div>`;}
 async function mutate(table,id,values){ctx.check(await ctx.db.from(table).update(values).eq('id',id).eq('store_id',store().id).select('id').single());await load(store().id);ctx.close();ctx.render();}
 function customerForm(k){const c=customers().find(c=>c.customer_key===k)||{};modal(c.customer_key?'تعديل العميل':'إضافة عميل',[['Name','الاسم',c.name,120],['Phone','الهاتف',c.phone,40],['Address','العنوان',c.address,500],['Province','المحافظة',c.province,80],['Group','المجموعة',c.customer_group,80],['Tags','الوسوم (افصل بفاصلة)',c.tags?.join('، '),500],['Note','ملاحظات',c.note,2000]].map(([id,label,value,max])=>`<label for="swCustomer${id}">${label}</label><input id="swCustomer${id}" maxlength="${max}" value="${E(value||'')}">`).join('')+btn('customerSave','حفظ',k||'','sw-primary'));}
 async function saveCustomer(k,patch){const c=customers().find(c=>c.customer_key===k);if(!c)return;if(c.id)return mutate('seller_customers',c.id,patch);ctx.check(await ctx.db.from('seller_customers').insert({store_id:store().id,customer_key:c.customer_key,buyer_id:c.buyer_id||null,name:c.name,phone:c.phone,address:c.address,...patch}));await load(store().id);ctx.close();ctx.render();}
 const actions={
 recordsBack:()=>{page='';query='';ctx.tab('settings');},customers:()=>{page='customers';query='';ctx.tab('settings');},categories:()=>{page='categories';query='';ctx.tab('settings');},
 categoryProducts:v=>{page='';h.category(v);},
 categoryForm:v=>{const c=categories.find(c=>c.id===v);modal(c?'تعديل التصنيف':'إضافة تصنيف',`<label for="swCategoryName">اسم التصنيف</label><input id="swCategoryName" maxlength="80" value="${E(c?.name||'')}">${btn('categorySave','حفظ',c?.id||'','sw-primary')}`);},
 categorySave:async v=>{const name=$('#swCategoryName').value.trim();if(!name){ctx.toast('اكتب اسم التصنيف');return;}if(v)ctx.check(await ctx.db.rpc('rename_seller_category',{p_id:v,p_name:name}));else ctx.check(await ctx.db.from('seller_categories').insert({store_id:store().id,name}));ctx.close();await ctx.refresh();ctx.toast('تم حفظ التصنيف');},
 categoryToggle:v=>{const c=categories.find(c=>c.id===v);if(c)return mutate('seller_categories',v,{active:!c.active});},
 categoryDelete:v=>modal('حذف التصنيف',`<p>سينتقل إلى التصنيفات المحذوفة ويمكن استعادته. تبقى منتجاته محفوظة.</p>${btn('categoryConfirmDelete','حذف التصنيف',v,'sw-primary')}`),categoryConfirmDelete:v=>mutate('seller_categories',v,{deleted_at:new Date().toISOString()}),categoryRestore:v=>mutate('seller_categories',v,{deleted_at:null}),
 categoryFilters:()=>modal('تصفية التصنيفات',select('swCategoryActive','الحالة',[['all','الكل'],['yes','فعال'],['no','غير فعال']],catFilter.active)+select('swCategoryDeleted','التصنيفات المحذوفة',[['active','النشطة فقط'],['deleted','المحذوفة فقط'],['both','النشطة والمحذوفة']],catFilter.deleted)+btn('categoryApply','تطبيق','','sw-primary')),
 categoryApply:()=>{catFilter={active:$('#swCategoryActive').value,deleted:$('#swCategoryDeleted').value};ctx.close();ctx.render();},
 customerForm,customerSave:async k=>{const name=$('#swCustomerName').value.trim();if(name.length<2){ctx.toast('اكتب اسم العميل');return;}const patch={name,phone:$('#swCustomerPhone').value.trim(),address:$('#swCustomerAddress').value.trim(),province:$('#swCustomerProvince').value.trim(),customer_group:$('#swCustomerGroup').value.trim(),tags:[...new Set($('#swCustomerTags').value.split(/[,،]/).map(s=>s.trim()).filter(Boolean))].slice(0,20),note:$('#swCustomerNote').value.trim()};if(k)await saveCustomer(k,patch);else{ctx.check(await ctx.db.from('seller_customers').insert({store_id:store().id,customer_key:'manual:'+crypto.randomUUID(),...patch}));await load(store().id);ctx.close();ctx.render();}ctx.toast('تم حفظ معلومات العميل');},
 customerDelete:k=>saveCustomer(k,{deleted_at:new Date().toISOString()}),customerRestore:k=>saveCustomer(k,{deleted_at:null}),
 customerBlock:k=>{const c=customers().find(c=>c.customer_key===k);if(!c?.buyer_id)return;modal(c.blocked?'رفع الحظر':'حظر الطلب من متجري',`<p>${E(c.name)}: ${c.blocked?'سيتمكن من الطلب مجددًا.':'لن يستطيع هذا الحساب إرسال طلب جديد لمتجرك. تبقى الطلبات السابقة محفوظة.'}</p>${btn('customerConfirmBlock',c.blocked?'رفع الحظر':'تأكيد الحظر',k,'sw-primary')}`);},customerConfirmBlock:k=>{const c=customers().find(c=>c.customer_key===k);if(c)return saveCustomer(k,{blocked:!c.blocked});},
 customerFields:()=>modal('المعلومات الظاهرة',`<label class="sw-check"><input type="checkbox" id="swCustomerAll" ${CF.every(x=>getSettings().customerFields.includes(x[0]))?'checked':''}>تحديد الكل</label>`+CF.map(([id,label])=>`<label class="sw-check"><input type="checkbox" name="swCustomerField" value="${id}" ${getSettings().customerFields.includes(id)?'checked':''}>${label}</label>`).join('')+btn('customerSaveFields','عرض وحفظ','','sw-primary')),
 customerSaveFields:async()=>{await saveConfig({...getSettings(),customerFields:[...document.querySelectorAll('[name="swCustomerField"]:checked')].map(e=>e.value)});ctx.close();ctx.render();},
 customerFilters:()=>{const all=customers(),opts=field=>[['','الكل'],...[...new Set(all.flatMap(c=>Array.isArray(c[field])?c[field]:[c[field]]).filter(Boolean))].map(v=>[v,v])];modal('تصفية العملاء',select('swCrProvince','المحافظة',opts('province'),filter.province)+select('swCrTag','الوسوم',opts('tags'),filter.tag)+select('swCrGroup','المجموعة',opts('customer_group'),filter.group)+select('swCrActivity','النشاط',[['','الكل'],['orders','لديه طلبات'],['none','دون طلبات']],filter.activity)+select('swCrBlocked','حالة الحظر',[['','الكل'],['yes','محظور'],['no','غير محظور']],filter.blocked)+select('swCrDeleted','العملاء المؤرشفون',[['active','النشطون فقط'],['deleted','المؤرشفون فقط'],['both','الكل']],filter.deleted)+`<div class="sw-dialog-actions">${btn('customerApply','تطبيق','','sw-primary')}${btn('customerClear','مسح')}</div>`);},
 customerApply:()=>{filter={province:$('#swCrProvince').value,tag:$('#swCrTag').value,group:$('#swCrGroup').value,activity:$('#swCrActivity').value,blocked:$('#swCrBlocked').value,deleted:$('#swCrDeleted').value};ctx.close();ctx.render();},customerClear:()=>{filter={deleted:'active'};ctx.close();ctx.render();},
 payments:()=>modal('المدفوعات',`<p>الدفع الحالي: نقدًا عند الاستلام.</p><div class="sw-summary"><span>قيمة المنتجات في الطلبات المكتملة</span><b>${ctx.fmt(orders().filter(o=>o.st===3).reduce((s,o)=>s+o.items.reduce((a,i)=>a+i.q*i.price,0),0))}</b></div><p class="sw-muted">هذا ملخص للطلبات المسلّمة، وليس إثباتًا لتحويل مالي.</p>`),
 shipping:()=>modal('الشحن والتوصيل',`<div class="sw-summary"><span>طلبات مسندة لسائق</span><b>${orders().filter(o=>o.driver_id&&o.st<3).length}</b></div><div class="sw-summary"><span>طلبات تنتظر الإسناد</span><b>${orders().filter(o=>!o.driver_id&&o.st<3).length}</b></div>${btn('recordOrders','متابعة الطلبات','','sw-primary')}`),recordOrders:()=>{page='';ctx.close();ctx.tab('chats');}
 };
 document.addEventListener('submit',e=>{if(e.target.id==='swRecordsSearch'){e.preventDefault();query=$('#swRecordsQuery').value.trim();ctx.render();}});
 document.addEventListener('change',e=>{if(e.target.id==='swCustomerAll')document.querySelectorAll('[name="swCustomerField"]').forEach(x=>x.checked=e.target.checked);});
 return {load,actions,render:()=>page==='customers'?customerPage():page==='categories'?categoryPage():null,reset:()=>{page='';query='';},categoryPage,names:()=>categories.filter(c=>c.active&&!c.deleted_at).map(c=>c.name)};
}
