/* Isolated real-browser UI checks. All orders and preferences belong to preview fixtures. */
const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),capture=process.env.SOUQ_CAPTURE;
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROME,args:['--no-sandbox']});
 try{
 const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('https://souq.test/**',async route=>{if(route.request().url().endsWith('harness.html'))return route.fulfill({contentType:'text/html',body:'<style>body{margin:0}iframe{width:100vw;height:100vh;border:0}</style><iframe src="https://souq.test/preview.html"></iframe>'});let file=path.join(root,new URL(route.request().url()).pathname);if(file.endsWith('/'))file+='index.html';if(!fs.existsSync(file))return route.abort();const types={'.html':'text/html','.js':'application/javascript','.css':'text/css','.png':'image/png','.svg':'image/svg+xml'};await route.fulfill({body:fs.readFileSync(file),contentType:types[path.extname(file)]||'application/octet-stream'});});
 await page.goto('https://souq.test/harness.html');let frame=page.frames().find(f=>f.url().includes('preview.html'));
 await frame.locator('[data-preview="role"][data-v="buyer"]').first().click();
 await frame.evaluate(async()=>{
  const {previewFixture}=await import('./preview-lab.js?v=109');const data=previewFixture(new Date().toISOString());
  const artwork=color=>'data:image/svg+xml;base64,'+btoa(`<svg xmlns="http://www.w3.org/2000/svg" width="320" height="400" viewBox="0 0 320 400"><path d="M125 75q35 32 70 0l67 33-25 75-37-18v190H120V165l-37 18-25-75z" fill="${color}" stroke="#442440" stroke-width="3"/><path d="M125 75q35 56 70 0" fill="none" stroke="#ffffff88" stroke-width="6"/><path d="M163 29q0-17 13-17t0 25l-61 37h101l-40-37" fill="none" stroke="#978998" stroke-width="4"/></svg>`);
  data.products[0].name='قميص ساتان';data.products[0].has_variants=true;data.products[0].image_path='shirt';data.products[0].stock=8;data.products[0].attributes={_manual_variants:true,_selling:{condition:'new',sale_mode:'retail'}};data.images.shirt=artwork('#dac6ac');
  data.product_variants=[['أسود','S',5,'black'],['بيج','M',3,'beige'],['بيج','XL',0,'beige']].map(([color,size,stock,image],i)=>({id:'a4000000-0000-4000-8000-00000000000'+(i+1),product_id:data.products[0].id,attributes:{color,size},label:color+' · '+size,price:10000,stock,available:true,archived:false,image_path:image}));data.images.black=artwork('#262230');data.images.beige=data.images.shirt;
  data.products[1].attributes={_selling:{condition:'used',sale_mode:'wholesale'}};data.products[1].category='تمور';data.products[1].image_path='dates';data.images.dates=artwork('#ad6883');data.products[2].image_path='bag';data.images.bag=artwork('#b4c5c3');
  data.stores[0].storefront_settings={color:'blue',mode:'light',icons:'outline'};
  localStorage.setItem('souq-shatra-interface-preview-v1',JSON.stringify(data));
 });
 await frame.goto('https://souq.test/preview.html');await frame.locator('[data-preview="role"][data-v="buyer"]').first().click();
 const snap=async name=>{if(capture)await page.screenshot({path:path.join(capture,name+'.png')});};
 await frame.evaluate(()=>window.SouqBuyerVoiceRuntime.show());await frame.locator('[data-gender="female"]').click();assert.equal(await frame.locator('#buyerVoiceDialog').count(),0);assert.equal(await frame.evaluate(()=>window.SouqBuyerVoiceRuntime.gender()),'female');
 assert.match(await frame.locator('#q').getAttribute('placeholder'),/ابحثي/);await snap('home');
 await frame.locator('#accountTrigger').click();assert.match(await frame.locator('#accountMenu').innerText(),/ملفي الشخصي وبياناتي/);assert.equal(await frame.locator('#accountMenu [data-a="enter"]').count(),0);await frame.locator('#accountMenu [data-v="profilePage"]').click();assert.match(await frame.locator('.profile-page').innerText(),/بيانات الحساب الأساسية/);
 await frame.locator('.tabs [data-v="stores"]').click();assert.equal(await frame.locator('.store-category-cards [data-v="تمور"]').count(),0);
 await frame.locator('.tabs [data-v="materials"]').click();await frame.locator('[data-a="materialType"][data-v="condition:used"]').click();assert.equal(await frame.locator('.mp-product-open').count(),1);await frame.locator('[data-a="materialType"][data-v="saleMode:retail"]').click();assert.equal(await frame.locator('.mp-product-open').count(),0);await frame.locator('[data-a="materialType"][data-v="condition:all"]').click();assert.equal(await frame.locator('.mp-product-open').count(),1);await frame.locator('[data-a="materialType"][data-v="saleMode:all"]').click();
 const iconColor=await frame.locator('.category-card svg').first().evaluate(el=>getComputedStyle(el).color);assert.equal(iconColor,'rgb(69, 32, 94)');
 await frame.locator('.tabs [data-v="market"]').click();

 await frame.locator('.mp-product-store').first().click();await frame.locator('.boutique-storebar').waitFor();assert.equal(await frame.locator('#sellerNav').count(),0);assert.match(await frame.locator('.boutique-store-hero').innerText(),/تسوقي/);await snap('store');
 await frame.locator('.sw-public-product').first().click();await frame.locator('.product-detail').waitFor();await frame.locator('[data-axis="color"][data-option="بيج"]').click();await frame.locator('[data-axis="size"][data-option="M"]').click();assert.equal(await frame.locator('[data-axis="size"][data-option="XL"]').isEnabled(),false);
 assert.match(await frame.locator('[data-a="add"]').innerText(),/أضيفي/);assert.equal(await frame.locator('.boutique-thumbnails button').count(),2);await frame.locator('.boutique-thumbnails button').last().click();await snap('product');
 for(const [width,height] of [[390,844],[820,1180],[1440,900]]){await page.setViewportSize({width,height});assert(await frame.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'page overflow '+width);assert(await frame.evaluate(()=>document.querySelector('#sheet').scrollWidth<=document.querySelector('#sheet').clientWidth+2),'detail overflow '+width);}
 await page.setViewportSize({width:390,height:844});await frame.locator('[data-a="addFromBar"]').click();await frame.locator('[data-a="cart"]').last().click();await frame.locator('#cn').fill('زبونة اختبار');await frame.locator('#cp').fill('07700000000');await frame.locator('#ca').fill('عنوان اختبار');await snap('cart');await frame.locator('[data-a="order"]').click();await frame.locator('.boutique-confirmation').waitFor();assert.match(await frame.locator('.boutique-confirmation h2').innerText(),/طلبكِ تم/);assert.equal(await frame.locator('.boutique-invoice .invoice-product').count(),1);await snap('confirmed');
 const data=await frame.evaluate(()=>JSON.parse(localStorage.getItem('souq-shatra-interface-preview-v1')));assert.equal(data.product_variants.find(v=>v.attributes.size==='M').stock,2);assert.equal(data.order_items[0].price,10000);assert.equal(data.orders[0].total,12500);
 await frame.locator('[data-preview="role"][data-v="seller"]').first().click();await frame.locator('[data-s="openMenu"]').click();assert.match(await frame.locator('#swDrawer').innerText(),/المخزن/);assert.equal(await frame.locator('#swDrawer nav button').count(),7);assert.deepEqual(await frame.locator('#swDrawer nav button').allTextContents(),['الملف الشخصي للبائع'+(await frame.locator('#swDrawer nav button small').innerText()),'الإشعارات','الطلبات','المخزن','المنتجات','الإعدادات','تسجيل الخروج']);assert.equal(await frame.locator('.sw-market-logo img').getAttribute('src'),'icons/brand-purple-v120.png');const rect=await frame.locator('.sw-seller-drawer').evaluate(el=>{const r=el.getBoundingClientRect();return {right:r.right,width:r.width}});assert.equal(rect.right,390);assert(rect.width<=390);assert.equal(await frame.locator('[data-s="openMenu"] svg path').getAttribute('d'),'M4 6h16M4 12h16M4 18h16');assert.equal(await frame.locator('#swDrawer [data-a="out"]').count(),1);await snap('seller-menu');await frame.locator('[data-s="menuStock"]').click();await frame.locator('.va-inventory').first().waitFor();assert.equal(await frame.locator('#swDrawer').count(),0);
 await frame.locator('[data-s="openMenu"]').click();await frame.locator('#swDrawer [data-v="settings"]').click();await frame.locator('[data-s="customize"]').click();assert.equal(await frame.locator('[data-s="draftColor"]').count(),0);await frame.locator('[data-s="saveCustomize"]').click();assert.equal(await frame.locator('.sw-sitebar').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(69, 32, 94)');
 await frame.locator('[data-preview="role"][data-v="buyer"]').first().click();assert.equal(await frame.evaluate(()=>window.SouqBuyerVoiceRuntime.gender()),'female');await frame.evaluate(()=>window.SouqBuyerVoiceRuntime.show());await frame.locator('[data-gender="male"]').click();assert.match(await frame.locator('#q').getAttribute('placeholder'),/^ابحث /);await frame.locator('[data-a="toggleTheme"]').first().click();await snap('home-dark');assert.equal(await frame.evaluate(()=>getComputedStyle(document.body).backgroundColor),'rgb(20, 14, 27)');
 const voicePage=page;await voicePage.setContent('<h1>تسوق الآن</h1><button id="shopping">أضف للسلة</button><p class="product-description">اكتب · وصف المنتج الأصلي</p>');await voicePage.addScriptTag({content:fs.readFileSync(path.join(root,'buyer-voice.js'),'utf8')});
 await voicePage.evaluate(()=>{window.voiceState={user:{id:'voice-account',user_metadata:{full_name:'اسم محفوظ'}},profile:null,mode:'buyer',ready:true,adminPortal:false,seller:false};window.preferenceWrites=[];window.voice=window.SouqBuyerVoice.create({get:()=>window.voiceState,db:{auth:{updateUser:async payload=>{window.preferenceWrites.push(payload);return {data:{user:window.voiceState.user},error:null}}}}});});
 assert.equal(await voicePage.locator('#buyerVoiceDialog').count(),0);await voicePage.evaluate(()=>{window.voiceState.profile={role:'buyer'};window.voice.sync();});await voicePage.locator('#buyerVoiceDialog').waitFor();await voicePage.locator('[data-gender="female"]').click();assert.equal(await voicePage.locator('#shopping').innerText(),'أضيفي للسلة');assert.equal(await voicePage.locator('.product-description').innerText(),'اكتب · وصف المنتج الأصلي');assert.deepEqual(await voicePage.evaluate(()=>window.preferenceWrites),[{data:{address_gender:'female'}}]);assert.equal(await voicePage.evaluate(()=>window.voiceState.user.user_metadata.full_name),'اسم محفوظ');await voicePage.close();
 assert.deepEqual(errors,[]);console.log('PASS: female/male preference, protected product names, real swatches/sizes/gallery, bottom add continuation, receipt from exact order, unchanged totals/stock, right drawer and exact seller menu/inventory/fixed brand color, phone/tablet/desktop, dark theme. No production writes.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
