import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
test('real requests remain visible across overlaps and adjacent work, without artificial navigation',async()=>{
 const jobs=new Map(),listeners={},text={textContent:''},panel={hidden:true,dataset:{},querySelector:()=>text};let id=0;
 const navigator={onLine:true},window={addEventListener:(event,fn)=>listeners[event]=fn};
 vm.runInNewContext(await readFile('main-loading.js','utf8'),{window,navigator,document:{getElementById:()=>panel},setTimeout:(fn,delay)=>{jobs.set(++id,{fn,delay});return id},clearTimeout:id=>jobs.delete(id)});
 const flush=delay=>{for(const [id,job] of [...jobs])if(job.delay===delay){jobs.delete(id);job.fn();}};
 window.SouqLoading.transition();assert.equal(panel.hidden,true);assert.equal(jobs.size,0);
 const quick=window.SouqLoading.begin();window.SouqLoading.end(quick);flush(220);assert.equal(panel.hidden,true);flush(180);
 const a=window.SouqLoading.begin(),b=window.SouqLoading.begin();flush(220);assert.equal(panel.hidden,false);
 window.SouqLoading.end(a);flush(180);assert.equal(panel.hidden,false);
 window.SouqLoading.end(b);assert.equal(panel.hidden,false);
 const c=window.SouqLoading.begin();flush(180);assert.equal(panel.hidden,false);
 window.SouqLoading.end(c);flush(180);assert.equal(panel.hidden,true);
 navigator.onLine=false;listeners.offline();assert.equal(panel.hidden,false);assert.match(text.textContent,/منقطع/);
 const d=window.SouqLoading.begin();navigator.onLine=true;listeners.online();flush(180);assert.equal(panel.hidden,false);
 window.SouqLoading.end(d);flush(180);assert.equal(panel.hidden,true);
});
