import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createProductEditor} from '../product-editor.js';
import {CATALOG_SEEDS} from '../category-seeds.js';
const category=CATALOG_SEEDS.find(c=>c.name==='قمصان وتيشيرتات').id;
function setup(product){const old=documentSafe(),nodes=new Map([['fs',{value:'10'}],['productSpecs',{innerHTML:''}],['veAxisName',{value:'السعة التخزينية'}]]),host={innerHTML:''};globalThis.document={getElementById:k=>nodes.get(k)||null};let price=1000;const editor=createProductEditor({categories:()=>CATALOG_SEEDS,toast:m=>{throw Error(m)},base:()=>({price}),upload:async()=> 'uploaded-variant.jpg'});editor.mount(host,product||{catalog_category_id:category,stock:10});const event=t=>({target:t,preventDefault(){}});return {editor,host,nodes,price:n=>price=n,change:(id,checked,value,dataset={})=>host.onchange(event({id,checked,value,dataset,type:'checkbox'})),input:(row,key,value)=>host.oninput(event({dataset:{veRow:String(row),veAttribute:key},value,type:'text'})),stock:(row,value)=>host.oninput(event({dataset:{veRow:String(row),veField:'stock'},value:String(value),type:'number'})),click:(ve,index,key)=>host.onclick(event({closest:()=>({dataset:{ve,index,key}})})),restore:()=>globalThis.document=old};}
function documentSafe(){return globalThis.document;}
test('ordinary product keeps stock, optional category, and closed variant controls',async()=>{const x=setup();try{assert(!x.host.innerHTML.includes('vstock0'));const b=await x.editor.collect();assert.equal(b.variants.length,0);assert.equal(b.expected_stock,10);assert.equal(b.catalog_category_id,category);x.change('vaCategory',false,'');assert.equal((await x.editor.collect()).catalog_category_id,CATALOG_SEEDS.find(c=>c.name==='ملابس').id);}finally{x.restore();}});
test('base and added variants are manual, inherit primary price/image, and have three independent balances',async()=>{const x=setup();try{x.change('vaEnabled',true);x.change('',true,'',{veAxis:'color'});x.change('',true,'',{veAxis:'size'});x.input(0,'color','أسود');x.input(0,'size','L');x.click('addRow');x.input(1,'color','أسود');x.input(1,'size','XL');x.stock(1,4);x.click('addRow');x.input(2,'color','أبيض');x.input(2,'size','L');x.stock(2,7);let b=await x.editor.collect();assert.equal(b.variants.length,3);assert.deepEqual(b.variants.map(v=>v.stock),[10,4,7]);assert(b.variants.every(v=>v.price===1000&&v.image_path===null));assert.equal(b.attributes._base_variant_id,b.variants[0].id);assert.equal(b.attributes._variant_inherit.length,3);assert(!b.variants.some(v=>v.attributes.color==='أبيض'&&v.attributes.size==='XL'));x.price(1250);assert((await x.editor.collect()).variants.every(v=>v.price===1250));x.input(2,'color','أسود');await assert.rejects(x.editor.collect(),/مكررة/);}finally{x.restore();}});
test('custom axis, price override and image override preserve identity and metadata across editing',async()=>{const x=setup();try{x.change('vaEnabled',true);x.click('addAxis');let html=x.host.innerHTML,key=/data-ve-attribute="(custom_[a-z0-9_]+)"/.exec(html)[1];x.input(0,key,'128GB');x.click('addRow');x.input(1,key,'256GB');x.stock(1,3);x.host.onchange({target:{dataset:{veRow:'1',veField:'inherit'},type:'checkbox',checked:true}});x.host.oninput({target:{dataset:{veRow:'1',veField:'price'},type:'number',value:'1700'}});const b=await x.editor.collect();assert.deepEqual(b.variants.map(v=>v.price),[1000,1700]);const old=b.variants.map((v,i)=>({...v,version:7+i,image_path:i?'variant.jpg':null}));x.editor.mount(x.host,{catalog_category_id:b.catalog_category_id,has_variants:true,stock:13,attributes:b.attributes,variants:old});const edited=await x.editor.collect();assert.deepEqual(edited.variants.map(v=>[v.id,v.version,v.stock,v.image_path]),old.map(v=>[v.id,v.version,v.stock,v.image_path]));assert.equal(edited.attributes._custom_options[0].label,'السعة التخزينية');assert.equal(edited.variants[1].price,1700);assert.throws(()=>x.click('removeCustom','0'),/أرشف/); }finally{x.restore();}});
test('custom section and category use existing product metadata instead of creating catalog records',async()=>{const x=setup();try{x.change('vaRoot',false,'other');x.host.oninput({target:{id:'veSection',value:'منتجات حرفية',dataset:{}}});x.host.oninput({target:{id:'veSubcategory',value:'خشب يدوي',dataset:{}}});const b=await x.editor.collect();assert.equal(b.catalog_category_id,null);assert.equal(b.category,'منتجات حرفية');assert.equal(b.attributes._selling.subcategory,'خشب يدوي');}finally{x.restore();}});

test('custom section exposes its optional category field immediately',()=>{const x=setup();try{x.change('vaRoot',false,'other');assert.match(x.host.innerHTML,/id="veSubcategory"/);}finally{x.restore();}});
test('selling unit is not duplicated among advanced specifications',()=>{const x=setup();try{assert(!x.nodes.get('productSpecs').innerHTML.includes('id="vaAttrsale_unit"'));}finally{x.restore();}});
test('adding an existing custom variant property reuses its identity',async()=>{const x=setup();try{x.change('vaEnabled',true);x.click('addAxis');let key=/data-ve-attribute="(custom_[a-z0-9_]+)"/.exec(x.host.innerHTML)[1];x.input(0,key,'128GB');x.click('addAxis');const b=await x.editor.collect();assert.equal(b.attributes._custom_options.length,1);assert.deepEqual(Object.keys(b.variants[0].attributes),[key]);}finally{x.restore();}});
test('existing custom specification can become a variant axis without a second definition',async()=>{const x=setup({catalog_category_id:category,stock:10,attributes:{_custom_options:[{key:'custom_storage',label:'السعة التخزينية',icon:'🏷️',type:'text',options:[],variant:false,required:false}]}});try{x.change('vaEnabled',true);x.click('addAxis');x.input(0,'custom_storage','256GB');const b=await x.editor.collect();assert.equal(b.attributes._custom_options.length,1);assert.equal(b.attributes._custom_options[0].variant,true);assert.equal(b.variants[0].attributes.custom_storage,'256GB');}finally{x.restore();}});
