/* Run with PLAYWRIGHT_CHROME pointing to a Chrome headless executable. No production writes. */
const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
(async()=>{
const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROME,args:['--no-sandbox','--single-process','--no-zygote']});
try{
const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{new MutationObserver(()=>{for(const el of document.querySelectorAll('#toast'))if(el.textContent.includes('تعذّر إكمال العملية'))window.__operationErrors=[...(window.__operationErrors||[]),el.textContent];}).observe(document,{subtree:true,childList:true,characterData:true});});
await page.route('https://souq.test/**',async route=>{if(route.request().url().endsWith('harness.html'))return route.fulfill({contentType:'text/html',body:'<style>body{margin:0}iframe{width:100vw;height:100vh;border:0}</style><iframe src="https://souq.test/preview.html"></iframe>'});let p=path.join(root,new URL(route.request().url()).pathname);if(p.endsWith('/'))p+='index.html';if(!fs.existsSync(p))return route.abort();const types={'.html':'text/html','.js':'application/javascript','.css':'text/css','.png':'image/png','.jpg':'image/jpeg'};await route.fulfill({body:fs.readFileSync(p),contentType:types[path.extname(p)]||'application/octet-stream'});});
await page.goto('https://souq.test/harness.html');await page.locator('iframe').waitFor();const f=page.frames().find(x=>x.url().includes('preview.html'));await f.locator('[data-preview="role"][data-v="seller"]').first().click();
await f.locator('[data-a="pform"][data-v=""]').first().click();
assert.equal(await f.locator('#productAdvanced').isVisible(),false);assert.equal(await f.locator('#fcost').count(),0);
assert.deepEqual(await f.locator('#funit option').allTextContents(),['قطعة','زوج','كيلوغرام','غرام','متر','أخرى']);
await f.locator('#fn').fill('قميص اختبار يدوي');await f.locator('#fd').fill('وصف تجريبي للمنتج');await f.locator('#fpr').fill('1000');await f.locator('#vaRoot').selectOption({label:'ملابس'});
await f.locator('#fcondition').selectOption('used');await f.locator('#fsaleMode').selectOption('wholesale');
await f.locator('#vaEnabled').check();await f.locator('[data-ve-axis="color"]').check();await f.locator('[data-ve-axis="size"]').check();
const attr=(i,k)=>f.locator(`[data-ve-row="${i}"][data-ve-attribute="${k}"]`);
await attr(0,'color').fill('أسود');await attr(0,'size').fill('L');await f.locator('#veBaseStock').fill('10');
await f.locator('[data-ve="addRow"]').click();await attr(1,'color').fill('أسود');await attr(1,'size').fill('XL');await f.locator('#vstock1').fill('4');await f.locator('[data-ve-row="1"][data-ve-field="inherit"]').check();await f.locator('#vprice1').fill('1700');
await f.locator('[data-ve="addRow"]').click();await attr(2,'color').fill('أبيض');await attr(2,'size').fill('L');await f.locator('#vstock2').fill('7');
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aX1UAAAAASUVORK5CYII=','base64');
await f.locator('#pimg').setInputFiles({name:'main.png',mimeType:'image/png',buffer:png});await f.locator('#pv img').waitFor();await f.locator('#vimage1').setInputFiles({name:'variant.png',mimeType:'image/png',buffer:png});
for(const [width,height] of [[390,844],[820,1180],[1440,900]]){await page.setViewportSize({width,height});assert(await f.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'product form overflows '+width);if(process.env.SOUQ_CAPTURE)await page.screenshot({path:process.env.SOUQ_CAPTURE+'/product-form-'+width+'.png'});}
await page.setViewportSize({width:390,height:844});await f.locator('[data-a="psave"]').click();await f.getByRole('button',{name:'قميص اختبار يدوي',exact:true}).waitFor();
const snapshot=()=>f.evaluate(()=>JSON.parse(localStorage.getItem('souq-shatra-interface-preview-v1')));let data=await snapshot(),p=data.products.find(x=>x.name==='قميص اختبار يدوي'),vs=data.product_variants.filter(x=>x.product_id===p.id);assert.equal(vs.length,3);assert.deepEqual(vs.map(v=>v.stock),[10,4,7]);assert.equal(p.price,1000);assert.equal(p.attributes._selling.condition,'used');assert.equal(p.attributes._selling.sale_mode,'wholesale');assert(vs[1].image_path);assert(vs[0].image_path===null);const ids=vs.map(v=>v.id);
await f.getByRole('button',{name:'قميص اختبار يدوي',exact:true}).click();await f.locator('.owner-product').waitFor();assert.equal(await f.locator('#productCreateForm').count(),0);await f.locator('.owner-product [data-a="pform"]').click();assert.equal(await f.locator('#fcondition').inputValue(),'used');assert.equal(await f.locator('#fsaleMode').inputValue(),'wholesale');await f.locator('#fpr').fill('1250');await f.locator('[data-a="psave"]').click();await f.getByRole('button',{name:'قميص اختبار يدوي',exact:true}).waitFor();data=await snapshot();vs=data.product_variants.filter(x=>x.product_id===p.id);assert.deepEqual(vs.map(v=>v.id),ids);assert.deepEqual(vs.map(v=>v.price),[1250,1700,1250]);
await f.locator('[data-preview="role"][data-v="buyer"]').first().click();await f.locator(`[data-a="prod"][data-v="${p.id}"]`).first().click();
await f.locator('[data-axis="color"][data-option="أسود"]').click();await f.locator('[data-axis="size"][data-option="XL"]').click();assert.equal(await f.locator('[data-axis="color"][data-option="أبيض"]').isEnabled(),false);assert((await f.locator('#productPrice').innerText()).includes('1,700'));assert.equal(await f.locator('#productPhoto img').count(),1);
await f.locator('#productQuantity').evaluate(el=>el.dataset.identity='stable');await f.locator('[data-a="pq"][data-v="1"]').click();await f.locator('[data-a="pq"][data-v="1"]').click();await f.locator('[data-a="pq"][data-v="-1"]').click();assert.equal(await f.locator('#productQuantity').textContent(),'2');assert.equal(await f.locator('#productQuantity').getAttribute('data-identity'),'stable');if(process.env.SOUQ_CAPTURE)await page.screenshot({path:process.env.SOUQ_CAPTURE+'/product-detail.png'});
await f.locator('[data-a="add"]').evaluate(el=>{el.click();el.click();});let cart=await f.evaluate(()=>JSON.parse(localStorage.getItem('souq-preview-cart-v1')).cart);assert.equal(cart.length,1);assert.equal(cart[0].vid,ids[1]);assert.equal(cart[0].q,2);assert.equal(cart[0].price,1700);assert.equal(cart[0].attributes.size,'XL');
await f.locator(`[data-a="prod"][data-v="${p.id}"]`).first().click();await f.locator('.product-seller-card').click();await f.locator('.sw-public-header').waitFor();assert((await f.locator('.sw-public-header').innerText()).includes('متجر المعاينة'));assert.equal(await f.locator('#productDetailBody').isVisible(),false);
for(const [width,height] of [[390,844],[820,1180],[1440,900]]){await page.setViewportSize({width,height});assert(await f.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'store overflows '+width);}
await f.locator('[data-a="cart"]').last().click();await f.locator('#cn').fill('اختبار زبون');await f.locator('#cp').fill('07700000000');await f.locator('#ca').fill('عنوان اختبار');await f.locator('[data-a="order"]').click();await f.locator('.buyer-receipt,.cart-receipt').first().waitFor({timeout:3000}).catch(()=>{});data=await snapshot();assert.equal(data.orders.length,1);assert.equal(data.product_variants.find(v=>v.id===ids[1]).stock,2);assert.equal(data.product_variants.find(v=>v.id===ids[0]).stock,10);assert.equal(data.order_items[0].variant_id,ids[1]);assert.equal(data.order_items[0].price,1700);
assert.deepEqual(errors,[]);assert.deepEqual(await f.evaluate(()=>window.__operationErrors||[]),[]);assert.equal(await f.locator('#auroraLoading').isVisible(),false);console.log('PASS: real browser seller create/edit, base/image/price inheritance, three manual stocks, phone/tablet/desktop layout, owner preview, variant chips, unavailable combinations, responsive quantity, duplicate-click guard, variant cart/order debit, real store navigation');
}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});

