import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import vm from 'node:vm';
const read=p=>fs.readFileSync(new URL('../'+p,import.meta.url),'utf8');
function fn(s,name){const i=s.indexOf('function '+name+'('),end=s.indexOf('\n}',i)+2;return (s.slice(i-6,i)==='async '?'async ':'')+s.slice(i,end);}
function setup(path,{point={lat:31.4,lon:46.1},failure=false}={}){
 const calls=[],fields={sellerFirst:'اسم',sellerLast:'صاحب المتجر',joinStoreName:'متجر الاختبار',joinPhone:'07700000000',joinAddress:'الشطرة — الحي',joinDescription:'مواد غذائية',joinStoreKind:'physical'},button={disabled:false,isConnected:true};
 const c={user:{id:'owner-id',email:'owner@example.test'},profile:{disabled:false},sellerJoinPoint:point,window:{SouqLocationPicker:{point:p=>p&&Number.isFinite(p.lat)&&Number.isFinite(p.lon)?p:null,url:p=>'https://www.google.com/maps?q='+p.lat+','+p.lon}},val:id=>fields[id],$:()=>button,toast:t=>calls.push(['toast',t]),db:{rpc:async(name,args)=>{calls.push(['rpc',name,args]);return failure?{error:Error('network failed')}:{data:'store-id'};}},check:r=>{if(r.error)throw r.error;return r.data},location:{assign:url=>calls.push(['navigate',url])},tab:'sellerJoin'};
 vm.createContext(c);vm.runInContext(fn(read(path),'submitSellerApplication'),c);return {c,calls,button};
}
for(const path of ['index.html','catalog.html','preview.html']){
 test(path+': saving selected map precedes direct WhatsApp navigation with complete data',async()=>{const {c,calls,button}=setup(path);await c.submitSellerApplication();const rpc=calls.find(x=>x[0]==='rpc'),nav=calls.find(x=>x[0]==='navigate');assert.equal(rpc[1],'request_seller_join_map');assert.equal(rpc[2].p_lat,31.4);assert.equal(rpc[2].p_lon,46.1);assert.ok(calls.indexOf(nav)>calls.indexOf(rpc));const url=new URL(nav[1]);assert.equal(url.pathname,'/9647837271707');const message=url.searchParams.get('text');for(const value of ['اسم صاحب المتجر','متجر الاختبار','owner-id','owner@example.test','https://www.google.com/maps?q=31.4,46.1'])assert.ok(message.includes(value));assert.equal(button.disabled,false);});
 test(path+': no map means no request or WhatsApp navigation',async()=>{const {c,calls}=setup(path,{point:null});await c.submitSellerApplication();assert.ok(!calls.some(x=>x[0]==='rpc'||x[0]==='navigate'));assert.ok(calls.some(x=>x[0]==='toast'));});
 test(path+': failed request does not open WhatsApp and unlocks retry',async()=>{const {c,calls,button}=setup(path,{failure:true});await assert.rejects(c.submitSellerApplication(),/network failed/);assert.ok(!calls.some(x=>x[0]==='navigate'));assert.equal(button.disabled,false);});
}
test('merchant picker uses map confirmation without losing typed form values',()=>{const s=read('index.html'),calls=[],card={innerHTML:''},c={sellerJoinPoint:null,window:{SouqLocationPicker:{show:o=>{calls.push(o);}}},sheet(){},head(){},A:{close:()=>calls.push('close')},$:()=>card,sellerJoinMapCard:()=>'<p>saved map</p>'};vm.createContext(c);vm.runInContext(fn(s,'chooseSellerLocation'),c);c.chooseSellerLocation();assert.equal(calls[0].purpose,'المتجر');calls[0].onConfirm({lat:31,lon:46});assert.equal(c.sellerJoinPoint.lat,31);assert.equal(card.innerHTML,'<p>saved map</p>');assert.ok(calls.includes('close'));assert.ok(!fn(s,'chooseSellerLocation').includes('render()'));});
test('direct admin acceptance sets approval true and never toggles a previously accepted seller',async()=>{const s=read('admin-app.js'),start=s.indexOf('approveProfessional:async'),end=s.indexOf(',professional:',start),code=s.slice(start,end);const calls=[],c={profile:{role:'admin',disabled:false},D:{m:[{id:'store-id',owner_id:'owner-id',ok:false,removed:false}]},refresh:async()=>calls.push('refresh'),check:r=>r.data,db:{rpc:async(name,args)=>{calls.push([name,args]);return {data:null};}},toast(){}};vm.createContext(c);vm.runInContext('callback=({'+code+'}).approveProfessional',c);await c.callback('seller','owner-id');assert.equal(calls.find(x=>Array.isArray(x))[0],'approve_store');assert.equal(calls.find(x=>Array.isArray(x))[1].p_approved,true);c.D.m[0].ok=true;calls.length=0;await c.callback('seller','owner-id');assert.ok(!calls.some(Array.isArray));});
test('map picker keeps checkout defaults and provides external maps link',()=>{const s=read('location-picker.js');assert.match(s,/title='اختيار موقع التوصيل'/);assert.match(s,/purpose='التوصيل'/);assert.match(s,/id="mapExternal"/);assert.match(s,/external.href=url\(p\)/);assert.match(s,/enableHighAccuracy:true/);});
