import {createClient} from 'https://esm.sh/@supabase/supabase-js@2.57.0';
import {SUPABASE_URL, SUPABASE_ANON_KEY} from './config.js';

const app=document.querySelector('#app');
const configured=SUPABASE_URL.startsWith('https://') && SUPABASE_ANON_KEY.length>30;
if(!configured){app.innerHTML='<section class="panel"><h2>النسخة المشتركة قيد الإعداد</h2><p>اربط قاعدة البيانات في <code>marketplace/config.js</code> ثم أعد تحميل الصفحة.</p></section>';throw Error('Supabase config missing')}
const db=createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
const $=s=>document.querySelector(s),fmt=n=>Number(n).toLocaleString('en-US')+' د.ع';
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID();
const CATS=['الدراجات وقطع الغيار','مواد غذائية','ملابس','أجهزة','منزلية','خدمات','أخرى'];
const S={view:'home',user:null,profile:null,store:null,stores:[],products:[],cart:[],selected:null,editing:null,filter:'',category:'الكل'};
try{S.cart=JSON.parse(localStorage.getItem('souq-cart-v2')||'[]')}catch{}
const saveCart=()=>{localStorage.setItem('souq-cart-v2',JSON.stringify(S.cart));$('#cart-count').textContent=S.cart.reduce((n,x)=>n+x.quantity,0)};
function notify(msg){const n=$('#notice');n.textContent=msg;n.hidden=false;clearTimeout(notify.timer);notify.timer=setTimeout(()=>n.hidden=true,4000)}
function fail(err){notify('تعذّر إكمال العملية: '+(err?.message||err))}
function check({data,error}){if(error)throw error;return data}
const image=p=>p.image_path?db.storage.from('products').getPublicUrl(p.image_path).data.publicUrl:'';
const storeOf=id=>S.stores.find(x=>x.id===id);
const product=id=>S.products.find(x=>x.id===id);
const card=p=>`<button class="card" data-product="${p.id}">${image(p)?`<img src="${e(image(p))}" alt="${e(p.name)}">`:'<div style="height:120px;display:grid;place-items:center;font-size:42px">📦</div>'}<h3>${e(p.name)}</h3><div class="small muted">${e(storeOf(p.store_id)?.name||'')}</div><div class="price">${fmt(p.price)}</div><span class="small">${p.stock?'المتوفر: '+p.stock:'نفدت الكمية'}</span></button>`;
async function loadCatalog(){
  const [stores,products]=await Promise.all([db.from('stores').select('*').order('created_at',{ascending:false}),db.from('products').select('*').order('created_at',{ascending:false})]);
  S.stores=check(stores);S.products=check(products);
}
async function loadAccount(){
  S.user=(await db.auth.getUser()).data.user;
  S.profile=null;S.store=null;
  if(!S.user)return;
  S.profile=check(await db.from('profiles').select('*').eq('id',S.user.id).single());
  const own=check(await db.from('stores').select('*').eq('owner_id',S.user.id).maybeSingle());
  S.store=own;
  if(own&&!S.stores.find(x=>x.id===own.id))S.stores.unshift(own);
}
function nav(){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('on',b.dataset.view===S.view));saveCart()}
function render(){nav();({home,storePage,productPage,cart:cartPage,orders:ordersPage,account:accountPage,cartPage,ordersPage,accountPage,productForm,storeForm,authPage,adminPage})[S.view]();window.scrollTo(0,0)}
function home(){
  const stores=S.stores.filter(x=>x.approved),products=S.products.filter(p=>p.active&&storeOf(p.store_id)?.approved&&p.name.includes(S.filter)&&(S.category==='الكل'||p.category===S.category));
  app.innerHTML=`<section class="panel"><h2>محلات الشطرة بين إيديك</h2><p class="muted">تصفح المحلات وقطع الغيار والبضائع، واطلب بالدفع عند الاستلام.</p><div class="row"><input id="search" placeholder="ابحث عن منتج" value="${e(S.filter)}"><select id="category">${['الكل',...CATS].map(c=>`<option ${S.category===c?'selected':''}>${e(c)}</option>`).join('')}</select></div></section>
  <h2>المحلات</h2>${stores.length?`<div class="cards">${stores.map(s=>`<button class="card" data-store="${s.id}"><h3>🏪 ${e(s.name)}</h3><div class="muted">${e(s.description||s.address)}</div></button>`).join('')}</div>`:'<p class="panel">بانتظار انضمام أول محل.</p>'}
  <h2>المنتجات</h2>${products.length?`<div class="cards">${products.map(card).join('')}</div>`:'<p class="panel">لا توجد منتجات مطابقة الآن.</p>'}`;
  $('#search').addEventListener('input',ev=>{S.filter=ev.target.value;home()});$('#category').addEventListener('change',ev=>{S.category=ev.target.value;home()});
}
function storePage(){const s=storeOf(S.selected);if(!s){S.view='home';render();return}const p=S.products.filter(x=>x.store_id===s.id&&x.active);app.innerHTML=`<button class="quiet" data-view="home">→ رجوع للسوق</button><section class="panel"><h2>🏪 ${e(s.name)}</h2><p>${e(s.description)}</p><p>📍 ${e(s.address)}</p><p>☎️ ${e(s.phone)} ${/^https:\/\//.test(s.social_url)?` · <a href="${e(s.social_url)}" target="_blank" rel="noopener noreferrer">التواصل مع المحل</a>`:''}</p></section><h2>بضاعة المحل</h2>${p.length?`<div class="cards">${p.map(card).join('')}</div>`:'<p class="panel">لا توجد بضاعة منشورة.</p>'}`}
function productPage(){const p=product(S.selected);if(!p){S.view='home';render();return}app.innerHTML=`<button class="quiet" data-store="${p.store_id}">→ صفحة المحل</button><section class="panel"><div class="row"><div>${image(p)?`<img class="preview" src="${e(image(p))}" alt="${e(p.name)}">`:''}</div><div><h2>${e(p.name)}</h2><p>${e(p.description)}</p><p class="muted">${e(p.category)} · ${e(storeOf(p.store_id)?.name)}</p><h3 class="price">${fmt(p.price)}</h3><p>المتوفر: ${p.stock}</p><button class="gold" data-add="${p.id}" ${p.stock?'':'disabled'}>أضف للسلة</button></div></div></section>`}
function cartPage(){const lines=S.cart.map(x=>({...x,p:product(x.id)})).filter(x=>x.p&&x.p.active);const total=lines.reduce((n,x)=>n+x.p.price*x.quantity,0);app.innerHTML=`<h2>سلة الشراء</h2>${lines.length?`<section class="panel">${lines.map(x=>`<div class="item"><b>${e(x.p.name)}</b> · ${fmt(x.p.price)}<div class="row"><span>الكمية: ${x.quantity}</span><button data-qty="${x.id}|1">+</button><button class="quiet" data-qty="${x.id}|-1">−</button></div></div>`).join('')}<h3>مجموع المنتجات: ${fmt(total)}</h3><p class="muted">أجرة التوصيل تؤكد عند الطلب. الطلب من أكثر من محل يُقسّم إلى طلب لكل محل.</p><button class="gold" data-view="checkout">إتمام الطلب</button></section>`:'<p class="panel">السلة فارغة.</p>'}`}
async function checkout(){if(!S.user){S.view='authPage';render();notify('سجّل الدخول لإرسال الطلب');return}const lines=S.cart.filter(x=>product(x.id));if(!lines.length){S.view='cartPage';render();return}app.innerHTML=`<h2>بيانات التوصيل</h2><form class="panel" id="checkout"><label>الاسم</label><input name="name" required minlength="2" value="${e(S.profile?.full_name)}"><label>رقم الهاتف</label><input name="phone" type="tel" required minlength="10" value="${e(S.profile?.phone)}"><label>العنوان داخل الشطرة</label><input name="address" required minlength="3" placeholder="الحي، الزقاق، أقرب نقطة دالة"><label>ملاحظات</label><textarea name="note"></textarea><button class="gold" type="submit">تأكيد الطلب · الدفع عند الاستلام</button></form>`;$('#checkout').onsubmit=submitOrder}
async function submitOrder(ev){ev.preventDefault();const b=ev.submitter;b.disabled=true;const f=new FormData(ev.target),groups=new Map();for(const x of S.cart){const p=product(x.id);if(!p)continue;if(!groups.has(p.store_id))groups.set(p.store_id,[]);groups.get(p.store_id).push({id:p.id,quantity:x.quantity})}const completed=[];try{for(const [store,lines] of groups){const id=check(await db.rpc('place_order',{p_store:store,p_lines:lines,p_name:f.get('name'),p_phone:f.get('phone'),p_address:f.get('address'),p_note:f.get('note')}));completed.push(id);S.cart=S.cart.filter(x=>!lines.some(y=>y.id===x.id));saveCart()}await loadCatalog();S.view='ordersPage';await ordersPage();notify('وصل طلبك: '+completed.map(x=>x.slice(0,8)).join('، '))}catch(err){fail(err);if(completed.length)notify('حُفظ '+completed.length+' طلب؛ راجع طلباتي قبل الإعادة')}finally{b.disabled=false}}
const status={new:'جديد',accepted:'مقبول',delivery:'خرج للتوصيل',delivered:'تم التسليم',cancelled:'ملغي'};
function orderCard(o,owner){return `<section class="panel"><div class="hero"><b>طلب #${e(o.id.slice(0,8))}</b><span class="tag">${status[o.status]}</span></div><p class="small muted">${new Date(o.created_at).toLocaleString('ar-IQ')}</p><p>${owner?e(o.customer_name)+' · '+e(o.customer_phone)+' · '+e(o.address):e(storeOf(o.store_id)?.name||'المحل')}</p><div>${(o.order_items||[]).map(i=>`<div class="item">${e(i.product_name)} × ${i.quantity} — ${fmt(i.price*i.quantity)}</div>`).join('')}</div><b>الإجمالي: ${fmt(o.total)}</b>${owner&&o.status!=='delivered'&&o.status!=='cancelled'?`<div class="row" style="margin-top:12px">${({new:'accepted',accepted:'delivery',delivery:'delivered'})[o.status]?`<button data-status="${o.id}|${{new:'accepted',accepted:'delivery',delivery:'delivered'}[o.status]}">تحديث حالة الطلب</button>`:''}<button class="danger" data-status="${o.id}|cancelled">إلغاء</button></div>`:''}</section>`}
async function ordersPage(){if(!S.user){app.innerHTML='<section class="panel">سجّل الدخول لرؤية طلباتك. <button data-view="authPage">دخول</button></section>';return}app.innerHTML='<p class="panel">جاري تحميل الطلبات…</p>';try{const orders=check(await db.from('orders').select('*,order_items(*)').eq('buyer_id',S.user.id).order('created_at',{ascending:false}));app.innerHTML=`<h2>طلباتي</h2>${orders.length?orders.map(o=>orderCard(o,false)).join(''):'<p class="panel">ليس لديك طلبات بعد.</p>'}`}catch(err){fail(err)}}
function authPage(){app.innerHTML=`<section class="panel"><h2>دخول أو حساب جديد</h2><p class="muted">حساب واحد يتيح لك الشراء، ويمكنك إنشاء متجر منه لاحقاً.</p><form id="auth"><label>الاسم (عند التسجيل)</label><input name="name"><label>البريد الإلكتروني</label><input name="email" type="email" required><label>كلمة المرور</label><input name="password" type="password" required minlength="6"><div class="row" style="margin-top:14px"><button type="submit" name="mode" value="in">دخول</button><button class="gold" type="submit" name="mode" value="up">حساب جديد</button></div></form></section>`;$('#auth').onsubmit=async ev=>{ev.preventDefault();const b=ev.submitter,before=b.disabled;b.disabled=true;try{const f=new FormData(ev.target),email=String(f.get('email')).trim(),password=String(f.get('password'));let result;if(b.value==='up'){if(String(f.get('name')).trim().length<2)throw Error('اكتب الاسم');result=await db.auth.signUp({email,password,options:{data:{full_name:f.get('name')}}})}else result=await db.auth.signInWithPassword({email,password});check(result);await loadAccount();S.view='accountPage';render();notify(S.user?'تم الدخول':'تحقق من بريدك الإلكتروني لتفعيل الحساب')}catch(err){fail(err)}finally{b.disabled=before}}}
function accountPage(){if(!S.user){S.view='authPage';authPage();return}let html=`<section class="panel"><div class="hero"><div><h2>حسابي</h2><span class="muted">${e(S.user.email)}</span></div><button class="quiet" data-logout>خروج</button></div></section>`;if(S.store){html+=`<section class="panel"><h2>🏪 ${e(S.store.name)}</h2><p class="${S.store.approved?'ok':'error'}">${S.store.approved?'المتجر منشور':'المتجر بانتظار موافقة الإدارة'}</p><div class="row"><button data-view="storeForm">تعديل معلومات المتجر</button><button class="gold" data-view="productForm">إضافة منتج</button></div></section><h2>منتجاتي</h2>${S.products.filter(p=>p.store_id===S.store.id).map(p=>`<div class="panel item"><b>${e(p.name)}</b> · ${fmt(p.price)} · المتوفر ${p.stock}<div class="row"><button data-edit="${p.id}">تعديل</button><button class="danger" data-delete="${p.id}">حذف</button></div></div>`).join('')||'<p class="panel">لم تضف منتجات.</p>'}<button data-view="sellerOrders">طلبات متجري</button>`}else html+='<section class="panel"><h2>لديك محل في الشطرة؟</h2><p>افتح صفحة محلك وانشر بضاعتك بنفسك.</p><button class="gold" data-view="storeForm">أنشئ متجر</button></section>';if(S.profile?.role==='admin')html+='<section class="panel"><button data-view="adminPage">لوحة إدارة السوق</button></section>';app.innerHTML=html}
function storeForm(){if(!S.user){S.view='authPage';render();return}const s=S.store||{};app.innerHTML=`<h2>${s.id?'تعديل المتجر':'تسجيل متجر جديد'}</h2><form class="panel" id="store-form"><label>اسم المحل</label><input name="name" required minlength="2" value="${e(s.name)}"><label>وصف المحل والخدمات</label><textarea name="description">${e(s.description)}</textarea><label>العنوان في الشطرة</label><input name="address" value="${e(s.address)}"><label>رقم التواصل</label><input name="phone" type="tel" value="${e(s.phone)}"><label>رابط صفحة التواصل (https://)</label><input name="social_url" type="url" value="${e(s.social_url)}"><button class="gold" type="submit">حفظ المتجر</button></form>`;$('#store-form').onsubmit=async ev=>{ev.preventDefault();const b=ev.submitter;b.disabled=true;try{const f=new FormData(ev.target),v=Object.fromEntries(f);if(s.id)check(await db.from('stores').update(v).eq('id',s.id));else check(await db.rpc('register_store',{p_name:v.name,p_phone:v.phone,p_address:v.address,p_description:v.description,p_social_url:v.social_url}));await loadAccount();await loadCatalog();S.view='accountPage';render();notify('تم حفظ المتجر. النشر يبدأ بعد موافقة الإدارة.')}catch(err){fail(err)}finally{b.disabled=false}}}
function productForm(){if(!S.store){S.view='accountPage';render();return}const p=S.editing?product(S.editing):null;app.innerHTML=`<h2>${p?'تعديل المنتج':'إضافة منتج'}</h2><form class="panel" id="product-form"><label>اسم المنتج</label><input name="name" required minlength="2" value="${e(p?.name)}"><label>السعر بالدينار</label><input name="price" type="number" min="1" required value="${p?.price||''}"><label>الكمية المتوفرة</label><input name="stock" type="number" min="0" required value="${p?.stock??0}"><label>التصنيف</label><select name="category">${CATS.map(c=>`<option ${p?.category===c?'selected':''}>${e(c)}</option>`).join('')}</select><label>الوصف</label><textarea name="description">${e(p?.description)}</textarea><label>صورة المنتج (اختياري، حتى 2 ميغابايت)</label><input name="image" type="file" accept="image/png,image/jpeg,image/webp">${p?.image_path?`<img class="preview" src="${e(image(p))}" alt="">`:''}<button class="gold" type="submit">حفظ المنتج</button></form>`;$('#product-form').onsubmit=async ev=>{ev.preventDefault();const b=ev.submitter;b.disabled=true;try{const f=new FormData(ev.target),file=f.get('image');let path=p?.image_path||null;if(file instanceof File&&file.size){if(file.size>2*1024*1024||!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('اختر صورة JPG أو PNG أو WebP بحجم أقل من 2 ميغابايت');path=`${S.store.id}/${uid()}.${file.type.split('/')[1]}`;check(await db.storage.from('products').upload(path,file,{contentType:file.type}))}const values={store_id:S.store.id,name:String(f.get('name')).trim(),price:Number(f.get('price')),stock:Number(f.get('stock')),category:f.get('category'),description:f.get('description'),image_path:path};if(p)check(await db.from('products').update(values).eq('id',p.id));else check(await db.from('products').insert(values));await loadCatalog();S.editing=null;S.view='accountPage';render();notify('تم حفظ المنتج')}catch(err){fail(err)}finally{b.disabled=false}}}
async function sellerOrders(){if(!S.store)return;app.innerHTML='<p class="panel">جاري تحميل الطلبات…</p>';try{const orders=check(await db.from('orders').select('*,order_items(*)').eq('store_id',S.store.id).order('created_at',{ascending:false}));app.innerHTML=`<h2>طلبات ${e(S.store.name)}</h2>${orders.length?orders.map(o=>orderCard(o,true)).join(''):'<p class="panel">لا توجد طلبات بعد.</p>'}`}catch(err){fail(err)}}
async function adminPage(){if(S.profile?.role!=='admin'){S.view='home';render();return}app.innerHTML='<p class="panel">جاري تحميل المتاجر…</p>';try{const stores=check(await db.from('stores').select('*').order('created_at',{ascending:false}));app.innerHTML=`<h2>إدارة المتاجر</h2>${stores.map(s=>`<section class="panel"><b>${e(s.name)}</b><p>${e(s.address)} · ${e(s.phone)}</p><button data-approve="${s.id}|${!s.approved}">${s.approved?'إيقاف المتجر':'الموافقة والنشر'}</button></section>`).join('')||'<p class="panel">لا توجد متاجر بعد.</p>'}`}catch(err){fail(err)}}
document.addEventListener('click',async ev=>{const b=ev.target.closest('button');if(!b)return;try{
  if(b.dataset.view){const v=b.dataset.view;if(v==='productForm')S.editing=null;S.view=v;if(v==='checkout')await checkout();else if(v==='sellerOrders')await sellerOrders();else render()}
  else if(b.dataset.store){S.selected=b.dataset.store;S.view='storePage';render()}
  else if(b.dataset.product){S.selected=b.dataset.product;S.view='productPage';render()}
  else if(b.dataset.add){const p=product(b.dataset.add),x=S.cart.find(x=>x.id===p.id);if(x)x.quantity=Math.min(p.stock,x.quantity+1);else S.cart.push({id:p.id,quantity:1});saveCart();notify('أُضيف للسلة')}
  else if(b.dataset.qty){const [id,delta]=b.dataset.qty.split('|'),x=S.cart.find(x=>x.id===id);x.quantity=Math.min(product(id).stock,x.quantity+Number(delta));S.cart=S.cart.filter(x=>x.quantity>0);saveCart();cartPage()}
  else if(b.dataset.edit){S.editing=b.dataset.edit;S.view='productForm';render()}
  else if(b.dataset.delete){if(!confirm('حذف المنتج؟'))return;check(await db.from('products').delete().eq('id',b.dataset.delete));await loadCatalog();render()}
  else if(b.dataset.status){const [id,status]=b.dataset.status.split('|');check(await db.rpc('set_order_status',{p_order:id,p_status:status}));await sellerOrders()}
  else if(b.dataset.approve){const [id,approved]=b.dataset.approve.split('|');check(await db.rpc('approve_store',{p_store:id,p_approved:approved==='true'}));await loadCatalog();await adminPage()}
  else if(b.hasAttribute('data-logout')){check(await db.auth.signOut());await loadAccount();S.view='home';render()}
}catch(err){fail(err)}});
await loadAccount().catch(fail);await loadCatalog().catch(fail);render();
